// packages/react/test-app/Pages/Flash/WithInfiniteScroll.tsx
import { InfiniteScroll, router, usePage } from '@lunajs/react'
import { useRef, useState } from 'react'

export default ({ users }: { users: { data: { id: number; name: string }[] } }) => {
  const page = usePage()
  const [flashEventCount, setFlashEventCount] = useState(0)
  const listenerSetup = useRef(false)

  if (!listenerSetup.current) {
    listenerSetup.current = true
    router.on('flash', () => {
      setFlashEventCount((n) => n + 1)
    })
  }

  return (
    <div>
      <span id="flash">{JSON.stringify(page.flash)}</span>
      <span id="flash-event-count">{flashEventCount}</span>

      <InfiniteScroll data="users" style={{ display: 'grid', gap: '20px' }}>
        {users.data.map((user) => (
          <div key={user.id} style={{ height: '15vh', border: '1px solid #ccc' }}>
            {user.name}
          </div>
        ))}
      </InfiniteScroll>
    </div>
  )
}

// packages/vue3/test-app/Pages/Flash/WithInfiniteScroll.vue
<script setup lang="ts">
import { InfiniteScroll, router, usePage } from '@lunajs/vue3'
import { ref } from 'vue'

defineProps<{
  users: {
    data: { id: number; name: string }[]
  }
}>()

const page = usePage()
const flashEventCount = ref(0)

router.on('flash', () => {
  flashEventCount.value++
})
</script>

<template>
  <div>
    <span id="flash">{{ JSON.stringify(page.flash) }}</span>
    <span id="flash-event-count">{{ flashEventCount }}</span>

    <InfiniteScroll data="users" style="display: grid; gap: 20px">
      <div v-for="user in users.data" :key="user.id" style="height: 15vh; border: 1px solid #ccc">
        {{ user.name }}
      </div>
    </InfiniteScroll>
  </div>
</template>
