// packages/svelte/test-app/Pages/Flash/WithDeferred.svelte
<script lang="ts">
  import { Deferred, page, router } from '@lunajs/svelte'

  interface Props {
    data: string | undefined
  }

  let { data }: Props = $props()

  let flashEventCount = $state(0)

  router.on('flash', () => {
    flashEventCount++
  })
</script>

<div>
  <span id="flash">{JSON.stringify(page.flash)}</span>
  <span id="flash-event-count">{flashEventCount}</span>

  <Deferred data="data">
    {#snippet fallback()}
      <div id="loading">Loading...</div>
    {/snippet}
    <div id="data">{data}</div>
  </Deferred>
</div>

// packages/vue3/test-app/Pages/Flash/WithDeferred.vue
<script setup lang="ts">
import { Deferred, router, usePage } from '@lunajs/vue3'
import { ref } from 'vue'

defineProps<{
  data?: string
}>()

const page = usePage()
const flashEventCount = ref(0)

router.on('flash', () => {
  flashEventCount.value++
})
</script>

<template>
  <div>
    <span id="flash">{{ JSON.stringify(page.flash) }}</span>
    <span id="flash-event-count">{{ flashEventCount }}</span>

    <Deferred data="data">
      <template #fallback>
        <div id="loading">Loading...</div>
      </template>
      <div id="data">{{ data }}</div>
    </Deferred>
  </div>
</template>
