// packages/react/test-app/Pages/Poll/DynamicData.tsx
import { Link, router, usePoll } from '@laraxgram/react'

export default ({ counter, last_received }: { counter: number; last_received: number | null }) => {
  usePoll(300, () => ({
    data: { counter_seen: counter },
    only: ['last_received'],
  }))

  return (
    <>
      <div id="counter">counter: {counter}</div>
      <div id="last_received">received: {last_received ?? 'null'}</div>
      <button onClick={() => router.reload({ only: ['counter'], data: { bump: counter + 1 } })}>Increment</button>
      <Link href="/">Home</Link>
    </>
  )
}

// packages/svelte/test-app/Pages/Poll/DynamicData.svelte
<script lang="ts">
  import { Link, router, usePoll } from '@laraxgram/svelte'

  let { counter, last_received } = $props()

  usePoll(300, () => ({
    data: { counter_seen: counter },
    only: ['last_received'],
  }))
</script>

<div id="counter">counter: {counter}</div>
<div id="last_received">received: {last_received ?? 'null'}</div>
<button onclick={() => router.reload({ only: ['counter'], data: { bump: counter + 1 } })}>Increment</button>
<Link href="/">Home</Link>
