// packages/react/test-app/Pages/Poll/PreserveErrors.tsx
import { useForm, usePage, usePoll } from '@laraxgram/react'

export default ({ time }: { time: number }) => {
  const { errors } = usePage().props as { errors?: { name?: string } }
  const form = useForm({ name: '' })

  const submit = () => {
    form.post('/poll/preserve-errors')
  }

  usePoll(300, {
    only: ['time'],
  })

  return (
    <>
      {errors?.name && <p id="page-error">{errors.name}</p>}
      {form.errors.name && <p id="form-error">{form.errors.name}</p>}

      <button type="button" onClick={submit}>
        Submit
      </button>

      <p id="time">Time: {time}</p>
    </>
  )
}

// packages/svelte/test-app/Pages/Poll/PreserveErrors.svelte
<script lang="ts">
  import { useForm, usePoll, page } from '@laraxgram/svelte'

  interface Props {
    time: number
  }

  let { time }: Props = $props()

  const form = useForm({ name: '' })

  const submit = () => {
    form.post('/poll/preserve-errors')
  }

  usePoll(300, {
    only: ['time'],
  })
</script>

{#if page.props.errors?.name}
  <p id="page-error">{page.props.errors.name}</p>
{/if}
{#if form.errors.name}
  <p id="form-error">{form.errors.name}</p>
{/if}

<button type="button" onclick={submit}>Submit</button>

<p id="time">Time: {time}</p>
