// packages/react/test-app/Pages/Poll/UnchangedData.tsx
import { usePoll } from '@lunajs/react'
import { useLayoutEffect, useState } from 'react'

export default () => {
  const [replaceStateCalls, setReplaceStateCalls] = useState(0)
  const [pollsFinished, setPollsFinished] = useState(0)

  useLayoutEffect(() => {
    const original = window.history.replaceState.bind(window.history)
    window.history.replaceState = function (...args) {
      setReplaceStateCalls((c) => c + 1)
      return original(...args)
    }
  }, [])

  usePoll(500, {
    only: ['custom_prop'],
    onFinish: () => setPollsFinished((c) => c + 1),
  })

  return (
    <div>
      <p>
        replaceState calls: <span className="replaceStateCalls">{replaceStateCalls}</span>
      </p>
      <p>
        polls finished: <span className="pollsFinished">{pollsFinished}</span>
      </p>
    </div>
  )
}

// packages/svelte/test-app/Pages/Poll/UnchangedData.svelte
<script lang="ts">
  import { usePoll } from '@lunajs/svelte'
  import { onMount } from 'svelte'

  let replaceStateCalls = $state(0)
  let pollsFinished = $state(0)

  onMount(() => {
    const original = window.history.replaceState.bind(window.history)
    window.history.replaceState = function (...args) {
      replaceStateCalls++
      return original(...args)
    }
  })

  usePoll(500, {
    only: ['custom_prop'],
    onFinish: () => pollsFinished++,
  })
</script>

<div>
  <p>replaceState calls: <span class="replaceStateCalls">{replaceStateCalls}</span></p>
  <p>polls finished: <span class="pollsFinished">{pollsFinished}</span></p>
</div>
