// packages/vue3/test-app/Pages/Visits/AsyncLocationVisit.vue
<script setup lang="ts">
import { router } from '@laraxgram/vue3'
import { onUnmounted, ref } from 'vue'

const draft = ref('')
const banner = ref('')
const bannerMode = ref(false)
const lastVersionChange = ref('')

onUnmounted(
  router.on('location', (event) => {
    lastVersionChange.value = String(event.detail.versionChange)

    if (bannerMode.value && event.detail.versionChange) {
      event.preventDefault()
      banner.value = 'A new version is available'
    }
  }),
)

const backgroundReload = () => {
  router.reload({ headers: { 'X-Simulate-Version-Change': '1' } })
}

const backgroundManualLocation = () => {
  router.reload({ headers: { 'X-Simulate-Manual-Location': '1' } })
}
</script>

<template>
  <div>
    <span class="text">This is the page that demonstrates async location visits</span>

    <input id="draft" v-model="draft" />

    <button @click="backgroundReload" class="reload">Background reload</button>
    <button @click="backgroundManualLocation" class="manual-location">Background manual location</button>
    <button @click="bannerMode = !bannerMode" class="banner-mode">Banner mode: {{ bannerMode }}</button>

    <span id="version-change">{{ lastVersionChange }}</span>
    <span id="banner">{{ banner }}</span>
  </div>
</template>

// packages/react/test-app/Pages/Visits/AsyncLocationVisit.tsx
import { router } from '@laraxgram/react'
import { useEffect, useRef, useState } from 'react'

export default () => {
  const [draft, setDraft] = useState('')
  const [banner, setBanner] = useState('')
  const [lastVersionChange, setLastVersionChange] = useState('')
  const bannerMode = useRef(false)
  const [bannerModeLabel, setBannerModeLabel] = useState(false)

  useEffect(() => {
    return router.on('location', (event) => {
      setLastVersionChange(String(event.detail.versionChange))

      if (bannerMode.current && event.detail.versionChange) {
        event.preventDefault()
        setBanner('A new version is available')
      }
    })
  }, [])

  const backgroundReload = () => {
    router.reload({ headers: { 'X-Simulate-Version-Change': '1' } })
  }

  const backgroundManualLocation = () => {
    router.reload({ headers: { 'X-Simulate-Manual-Location': '1' } })
  }

  const toggleBannerMode = () => {
    bannerMode.current = !bannerMode.current
    setBannerModeLabel(bannerMode.current)
  }

  return (
    <div>
      <span className="text">This is the page that demonstrates async location visits</span>

      <input id="draft" value={draft} onChange={(e) => setDraft(e.target.value)} />

      <button onClick={backgroundReload} className="reload">
        Background reload
      </button>
      <button onClick={backgroundManualLocation} className="manual-location">
        Background manual location
      </button>
      <button onClick={toggleBannerMode} className="banner-mode">
        Banner mode: {String(bannerModeLabel)}
      </button>

      <span id="version-change">{lastVersionChange}</span>
      <span id="banner">{banner}</span>
    </div>
  )
}
