// packages/svelte/test-app/Pages/Visits/PreserveScroll.svelte
<script module lang="ts">
  export { default as layout } from '@/Layouts/WithScrollRegion.svelte'
</script>

<script lang="ts">
  import { router } from '@lunajs/svelte'

  const { foo = 'default' }: { foo?: string } = $props()

  const preserve = (e: Event) => {
    e.preventDefault()

    router.visit('/visits/preserve-scroll-page-two', {
      data: { foo: 'foo' },
      preserveScroll: true,
    })
  }

  const preserveFalse = (e: Event) => {
    e.preventDefault()

    router.visit('/visits/preserve-scroll-page-two', {
      data: { foo: 'bar' },
    })
  }

  const preserveCallback = (e: Event) => {
    e.preventDefault()

    router.visit('/visits/preserve-scroll-page-two', {
      data: { foo: 'baz' },
      preserveScroll: (page) => {
        console.log(JSON.stringify(page))

        return true
      },
    })
  }

  const preserveCallbackFalse = (e: Event) => {
    e.preventDefault()

    router.visit('/visits/preserve-scroll-page-two', {
      data: { foo: 'foo' },
      preserveScroll: (page) => {
        console.log(JSON.stringify(page))

        return false
      },
    })
  }

  const preserveGet = (e: Event) => {
    e.preventDefault()

    router.get(
      '/visits/preserve-scroll-page-two',
      {
        foo: 'bar',
      },
      {
        preserveScroll: true,
      },
    )
  }

  const preserveGetFalse = (e: Event) => {
    e.preventDefault()

    router.get('/visits/preserve-scroll-page-two', {
      foo: 'baz',
    })
  }
</script>

<div style="height: 800px; width: 600px">
  <span class="text">
    This is the page that demonstrates scroll preservation with scroll regions when using manual visits
  </span>
  <span class="foo">Foo is now {foo}</span>

  <a href={'#'} onclick={preserve} class="preserve">Preserve Scroll</a>
  <a href={'#'} onclick={preserveFalse} class="reset">Reset Scroll</a>
  <a href={'#'} onclick={preserveCallback} class="preserve-callback">Preserve Scroll (Callback)</a>
  <br />
  <a href={'#'} onclick={preserveCallbackFalse} class="reset-callback">Reset Scroll (Callback)</a>
  <a href={'#'} onclick={preserveGet} class="preserve-get">Preserve Scroll (GET)</a>
  <a href={'#'} onclick={preserveGetFalse} class="reset-get">Reset Scroll (GET)</a>

  <a href="/non-luna" class="off-site">Off-site link</a>
</div>

// packages/react/test-app/Pages/Visits/PreserveScroll.tsx
import { router } from '@lunajs/react'
import WithScrollRegion from '@/Layouts/WithScrollRegion.jsx'

const PreserveScroll = ({ foo = 'default' }) => {
  const preserve = (e: React.MouseEvent) => {
    e.preventDefault()
    router.visit('/visits/preserve-scroll-page-two', { data: { foo: 'foo' }, preserveScroll: true })
  }

  const preserveFalse = (e: React.MouseEvent) => {
    e.preventDefault()
    router.visit('/visits/preserve-scroll-page-two', { data: { foo: 'bar' } })
  }

  const preserveCallback = (e: React.MouseEvent) => {
    e.preventDefault()
    router.visit('/visits/preserve-scroll-page-two', {
      data: { foo: 'baz' },
      preserveScroll: (page) => {
        console.log(JSON.stringify(page))
        return true
      },
    })
  }

  const preserveCallbackFalse = (e: React.MouseEvent) => {
    e.preventDefault()
    router.visit('/visits/preserve-scroll-page-two', {
      data: { foo: 'foo' },
      preserveScroll: (page) => {
        console.log(JSON.stringify(page))
        return false
      },
    })
  }

  const preserveGet = (e: React.MouseEvent) => {
    e.preventDefault()
    router.get(
      '/visits/preserve-scroll-page-two',
      { foo: 'bar' },
      {
        preserveScroll: true,
      },
    )
  }

  const preserveGetFalse = (e: React.MouseEvent) => {
    e.preventDefault()
    router.get('/visits/preserve-scroll-page-two', { foo: 'baz' })
  }

  return (
    <div style={{ height: '800px', width: '600px' }}>
      <span className="text">
        This is the page that demonstrates scroll preservation with scroll regions when using manual visits
      </span>
      <span className="foo">Foo is now {foo}</span>

      <a href="#" onClick={preserve} className="preserve">
        Preserve Scroll
      </a>
      <a href="#" onClick={preserveFalse} data-testid="reset" className="reset">
        Reset Scroll
      </a>
      <a href="#" onClick={preserveCallback} className="preserve-callback">
        Preserve Scroll (Callback)
      </a>
      <br />
      <a href="#" onClick={preserveCallbackFalse} className="reset-callback">
        Reset Scroll (Callback)
      </a>
      <a href="#" onClick={preserveGet} className="preserve-get">
        Preserve Scroll (GET)
      </a>
      <a href="#" onClick={preserveGetFalse} className="reset-get">
        Reset Scroll (GET)
      </a>

      <a href="/non-luna" className="off-site">
        Off-site link
      </a>
    </div>
  )
}

PreserveScroll.layout = (page: React.ReactNode) => <WithScrollRegion children={page} />

export default PreserveScroll
