// packages/svelte/test-app/Pages/Visits/Wayfinder.svelte
<script lang="ts">
  import { router } from '@lunajs/svelte'

  const wayfinderObjectVisit = () => {
    router.visit({ url: '/dump/post', method: 'post' })
  }

  const wayfinderObjectMethodOverride = () => {
    router.visit({ url: '/dump/patch', method: 'get' }, { method: 'patch' })
  }
</script>

<div>
  <a href={'#'} onclick={wayfinderObjectVisit} class="wayfinder-visit">Wayfinder object visit</a>
  <a href={'#'} onclick={wayfinderObjectMethodOverride} class="wayfinder-method-override"
    >Wayfinder object method override</a
  >
</div>

// packages/react/test-app/Pages/Visits/Wayfinder.tsx
import { router } from '@lunajs/react'

export default function Wayfinder() {
  const wayfinderObjectVisit = (e: React.MouseEvent) => {
    e.preventDefault()
    router.visit({ url: '/dump/post', method: 'post' })
  }

  const wayfinderObjectMethodOverride = (e: React.MouseEvent) => {
    e.preventDefault()
    router.visit({ url: '/dump/patch', method: 'get' }, { method: 'patch' })
  }

  return (
    <div>
      <a href="#" onClick={wayfinderObjectVisit} className="wayfinder-visit">
        Wayfinder object visit
      </a>
      <a href="#" onClick={wayfinderObjectMethodOverride} className="wayfinder-method-override">
        Wayfinder object method override
      </a>
    </div>
  )
}
