// packages/vue3/test-app/Pages/Dump.vue
<script setup lang="ts">
import { Method } from '@lunajs/core'
import { usePage } from '@lunajs/vue3'
import { onBeforeMount } from 'vue'
import type { MulterFile } from '../types'

const props = defineProps<{
  headers: Record<string, string>
  method: Method
  form: Record<string, unknown> | undefined
  files: MulterFile[] | object
  query: Record<string, unknown>
  url: string
}>()

const page = usePage()

const dump = {
  headers: props.headers,
  method: props.method,
  form: props.form,
  files: props.files ? props.files : {},
  query: props.query,
  url: props.url,
  $page: page,
}

onBeforeMount(() => {
  window._luna_request_dump = dump
})
</script>

<template>
  <div>
    <div class="text">This is Luna page component containing a data dump of the request</div>
    <hr />
    <pre class="dump">{{ dump }}</pre>
  </div>
</template>

// packages/react/test-app/Pages/Dump.tsx
import type { Method } from '@lunajs/core'
import { usePage } from '@lunajs/react'
import { useEffect, useMemo } from 'react'
import type { MulterFile } from '../types'

export default ({
  headers,
  method,
  form,
  query,
  url,
  files,
}: {
  headers: Record<string, string>
  method: Method
  form: Record<string, unknown>
  query: Record<string, unknown>
  url: string
  files: MulterFile[] | object
}) => {
  const page = usePage()

  const dump = useMemo(
    () => ({
      headers,
      method,
      form,
      files: files ? files : {},
      query,
      url,
      $page: page,
    }),
    [headers, method, form, files, query, url, page],
  )

  useEffect(() => {
    window._luna_request_dump = dump
  }, [dump])

  return (
    <div>
      <div className="text">This is Luna page component containing a data dump of the request</div>
      <hr />
      <pre className="dump">{JSON.stringify(dump, null, 2)}</pre>
    </div>
  )
}
