// packages/vue3/test-app/Pages/Home.vue
<script setup lang="ts">
import { Head, Link, router } from '@lunajs/vue3'
import { getCurrentInstance } from 'vue'

const props = defineProps({
  example: String,
})

const visitsMethod = () => {
  router.visit('/visits/method')
}

const visitsReplace = () => {
  router.get('/visits/replace')
}

const redirect = () => {
  router.post('/redirect')
}

const redirectExternal = () => {
  router.post('/redirect-external')
}

const redirectHash = () => {
  router.get('/redirect-hash')
}

const redirectHashPost = () => {
  router.post('/redirect-hash')
}

window._luna_page_key = getCurrentInstance()?.uid
window._luna_props = props
window._plugin_global_props = getCurrentInstance()?.appContext.config.globalProperties || {}
</script>

<template>
  <Head title="Home" />

  <div>
    <span class="text">This is the Test App Entrypoint page</span>

    <Link href="/links/method" class="links-method">Basic Links</Link>
    <Link href="/links/replace" class="links-replace">'Replace' Links</Link>
    <Link href="/links/as-component" class="links-as-component">Custom Component</Link>

    <a href="#" @click.prevent="visitsMethod" class="visits-method">Manual basic visits</a>
    <a href="#" @click.prevent="visitsReplace" class="visits-replace">Manual 'Replace' visits</a>

    <Link href="/redirect" method="post" class="links-redirect">Internal Redirect Link</Link>
    <a href="#" @click.prevent="redirect" class="visits-redirect">Manual Redirect visit</a>

    <Link href="/redirect-external" method="post" class="links-redirect-external">External Redirect Link</Link>
    <a href="#" @click.prevent="redirectExternal" class="visits-redirect-external">Manual External Redirect visit</a>

    <a href="#" @click.prevent="redirectHash" class="visits-redirect-hash">Manual Hash Redirect visit</a>
    <a href="#" @click.prevent="redirectHashPost" class="visits-redirect-hash-post">Manual Hash Redirect POST visit</a>

    <Link id="navigate-back" href="/head/mixed">Go to Mixed Head</Link>

    <Link href="/links/as-element" className="link-targets-self" target="_self">Target _self</Link>
    <Link href="/links/as-element" className="link-targets-blank" target="_blank">Target _blank</Link>
  </div>
</template>

// packages/react/test-app/Pages/Home.tsx
import { Head, Link, router } from '@lunajs/react'

export default (props: { example: string }) => {
  const visitsMethod = (e: React.MouseEvent) => {
    e.preventDefault()
    router.visit('/visits/method')
  }

  const visitsReplace = (e: React.MouseEvent) => {
    e.preventDefault()
    router.get('/visits/replace')
  }

  const redirect = (e: React.MouseEvent) => {
    e.preventDefault()
    router.post('/redirect')
  }

  const redirectExternal = (e: React.MouseEvent) => {
    e.preventDefault()
    router.post('/redirect-external')
  }

  const redirectHash = (e: React.MouseEvent) => {
    e.preventDefault()
    router.get('/redirect-hash')
  }

  const redirectHashPost = (e: React.MouseEvent) => {
    e.preventDefault()
    router.post('/redirect-hash')
  }

  // window._luna_page_key = getCurrentInstance().uid
  window._luna_props = props
  // window._plugin_global_props = getCurrentInstance().appContext.config.globalProperties

  return (
    <>
      <Head title="Home" />

      <div>
        <span className="text">This is the Test App Entrypoint page</span>

        <Link href="/links/method" className="links-method">
          Basic Links
        </Link>

        <Link href="/links/replace" className="links-replace">
          'Replace' Links
        </Link>

        <Link href="/links/as-component" className="links-as-component">
          As Component
        </Link>

        <Link href="/links/as-element" className="links-as-component">
          As Element
        </Link>

        <a href="#" onClick={visitsMethod} className="visits-method">
          Manual basic visits
        </a>

        <a href="#" onClick={visitsReplace} className="visits-replace">
          Manual 'Replace' visits
        </a>

        <Link href="/redirect" method="post" className="links-redirect">
          Internal Redirect Link
        </Link>
        <a href="#" onClick={redirect} className="visits-redirect">
          Manual Redirect visit
        </a>

        <Link href="/redirect-external" method="post" className="links-redirect-external">
          External Redirect Link
        </Link>

        <a href="#" onClick={redirectExternal} className="visits-redirect-external">
          Manual External Redirect visit
        </a>

        <a href="#" onClick={redirectHash} className="visits-redirect-hash">
          Manual Hash Redirect visit
        </a>

        <a href="#" onClick={redirectHashPost} className="visits-redirect-hash-post">
          Manual Hash Redirect POST visit
        </a>

        <Link id="navigate-back" href="/head/mixed">
          Go to Mixed Head
        </Link>

        <Link href="/links/as-element" className="link-targets-self" target="_self">
          Target _self
        </Link>
        <Link href="/links/as-element" className="link-targets-blank" target="_blank">
          Target _blank
        </Link>
      </div>
    </>
  )
}
