// packages/svelte/test-app/Pages/Home.svelte
<script lang="ts">
  import { luna, page, router } from '@lunajs/svelte'
  import { onMount } from 'svelte'

  const visitsMethod = () => {
    router.visit('/visits/method')
  }

  const visitsReplace = () => {
    router.get('/visits/replace')
  }

  const redirect = () => {
    router.post('/redirect')
  }

  const redirectExternal = () => {
    router.post('/redirect-external')
  }

  const redirectHash = () => {
    router.get('/redirect-hash')
  }

  const redirectHashPost = () => {
    router.post('/redirect-hash')
  }

  onMount(() => {
    window._luna_page_key = crypto.randomUUID()
    window._luna_props = page.props
    window._plugin_global_props = {}
  })
</script>

<div>
  <span class="text">This is the Test App Entrypoint page</span>

  <a href="/links/method" use:luna class="links-method">Basic Links</a>
  <a href="/links/replace" use:luna class="links-replace">'Replace' Links</a>

  <a href={'#'} onclick={visitsMethod} class="visits-method">Manual basic visits</a>
  <a href={'#'} onclick={visitsReplace} class="visits-replace">Manual 'Replace' visits</a>

  <button use:luna={{ href: '/redirect', method: 'post' }} class="links-redirect">Internal Redirect Link</button>
  <a href={'#'} onclick={redirect} class="visits-redirect">Manual Redirect visit</a>

  <button use:luna={{ href: '/redirect-external', method: 'post' }} class="links-redirect-external"
    >External Redirect Link</button
  >
  <a href={'#'} onclick={redirectExternal} class="visits-redirect-external">Manual External Redirect visit</a>

  <a href={'#'} onclick={redirectHash} class="visits-redirect-hash">Manual Hash Redirect visit</a>
  <a href={'#'} onclick={redirectHashPost} class="visits-redirect-hash-post">Manual Hash Redirect POST visit</a>

  <a href="/links/as-element" use:luna class="link-targets-self" target="_self">Target _self</a>
  <a href="/links/as-element" use:luna class="link-targets-blank" target="_blank">Target _blank</a>
</div>

// packages/react/test-app/Pages/Home.tsx
import { Head, Link, router } from '@lunajs/react'

export default (props: { example: string }) => {
  const visitsMethod = (e: React.MouseEvent) => {
    e.preventDefault()
    router.visit('/visits/method')
  }

  const visitsReplace = (e: React.MouseEvent) => {
    e.preventDefault()
    router.get('/visits/replace')
  }

  const redirect = (e: React.MouseEvent) => {
    e.preventDefault()
    router.post('/redirect')
  }

  const redirectExternal = (e: React.MouseEvent) => {
    e.preventDefault()
    router.post('/redirect-external')
  }

  const redirectHash = (e: React.MouseEvent) => {
    e.preventDefault()
    router.get('/redirect-hash')
  }

  const redirectHashPost = (e: React.MouseEvent) => {
    e.preventDefault()
    router.post('/redirect-hash')
  }

  // window._luna_page_key = getCurrentInstance().uid
  window._luna_props = props
  // window._plugin_global_props = getCurrentInstance().appContext.config.globalProperties

  return (
    <>
      <Head title="Home" />

      <div>
        <span className="text">This is the Test App Entrypoint page</span>

        <Link href="/links/method" className="links-method">
          Basic Links
        </Link>

        <Link href="/links/replace" className="links-replace">
          'Replace' Links
        </Link>

        <Link href="/links/as-component" className="links-as-component">
          As Component
        </Link>

        <Link href="/links/as-element" className="links-as-component">
          As Element
        </Link>

        <a href="#" onClick={visitsMethod} className="visits-method">
          Manual basic visits
        </a>

        <a href="#" onClick={visitsReplace} className="visits-replace">
          Manual 'Replace' visits
        </a>

        <Link href="/redirect" method="post" className="links-redirect">
          Internal Redirect Link
        </Link>
        <a href="#" onClick={redirect} className="visits-redirect">
          Manual Redirect visit
        </a>

        <Link href="/redirect-external" method="post" className="links-redirect-external">
          External Redirect Link
        </Link>

        <a href="#" onClick={redirectExternal} className="visits-redirect-external">
          Manual External Redirect visit
        </a>

        <a href="#" onClick={redirectHash} className="visits-redirect-hash">
          Manual Hash Redirect visit
        </a>

        <a href="#" onClick={redirectHashPost} className="visits-redirect-hash-post">
          Manual Hash Redirect POST visit
        </a>

        <Link id="navigate-back" href="/head/mixed">
          Go to Mixed Head
        </Link>

        <Link href="/links/as-element" className="link-targets-self" target="_self">
          Target _self
        </Link>
        <Link href="/links/as-element" className="link-targets-blank" target="_blank">
          Target _blank
        </Link>
      </div>
    </>
  )
}
