// packages/vue3/test-app/Pages/PreserveEqualProps.vue
<script setup lang="ts">
import { Link } from '@lunajs/vue3'
import { ref, watch } from 'vue'

const props = defineProps<{
  nestedA: { count: number }
  nestedB: { date: number }
}>()

const effectACount = ref(1)
const effectBCount = ref(1)

watch(
  () => props.nestedA,
  () => {
    effectACount.value++
  },
)

watch(
  () => props.nestedB,
  () => {
    effectBCount.value++
  },
)
</script>

<template>
  <div>
    <h1>Preserve Equal Props</h1>
    <p id="count-a">Count A: {{ nestedA.count }}</p>
    <p id="date-b">Date B: {{ nestedB.date }}</p>
    <p id="effect-a">Effect A Count: {{ effectACount }}</p>
    <p id="effect-b">Effect B Count: {{ effectBCount }}</p>
    <Link method="post" preserve-state href="/preserve-equal-props/back"> Submit and redirect back </Link>
  </div>
</template>

// packages/react/test-app/Pages/PreserveEqualProps.tsx
import { Link } from '@lunajs/react'
import { useEffect, useState } from 'react'

export default ({ nestedA, nestedB }: { nestedA: { count: number }; nestedB: { date: number } }) => {
  const [effectACount, setEffectACount] = useState(0)
  const [effectBCount, setEffectBCount] = useState(0)

  useEffect(() => {
    setEffectACount((count) => count + 1)
  }, [nestedA])

  useEffect(() => {
    setEffectBCount((count) => count + 1)
  }, [nestedB])

  return (
    <div>
      <h1>Preserve Equal Props</h1>
      <p id="count-a">Count A: {nestedA.count}</p>
      <p id="date-b">Date B: {nestedB.date}</p>
      <p id="effect-a">Effect A Count: {effectACount}</p>
      <p id="effect-b">Effect B Count: {effectBCount}</p>
      <Link method="post" href="/preserve-equal-props/back">
        Submit and redirect back
      </Link>
    </div>
  )
}
