// packages/react/test-app/Pages/Links/AsWarning.tsx
import type { Method } from '@lunajs/core'
import { Link } from '@lunajs/react'

export default ({ method }: { method: Method }) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates luna-links with an 'as' warning</span>

      <Link method={method} href="/example" className="get">
        {method} Link
      </Link>
    </div>
  )
}

// packages/vue3/test-app/Pages/Links/AsWarning.vue
<script setup lang="ts">
import type { Method } from '@lunajs/core'
import { Link } from '@lunajs/vue3'

defineProps<{
  method: Method
}>()
</script>

<template>
  <div>
    <span class="text">This is the links page that demonstrates luna-links with an 'as' warning</span>

    <Link :method="method" href="/example" class="get">{{ method }} Link</Link>
  </div>
</template>
