// packages/react/test-app/Pages/Links/PreserveState.tsx
import type { Page } from '@laraxgram/luna'
import { Link } from '@laraxgram/react'
import { useId } from 'react'
import WithoutScrollRegion from '@/Layouts/WithoutScrollRegion.jsx'

const PreserveState = ({ foo = 'default' }: { foo?: string }) => {
  const preserveCallback = (page: Page) => {
    alert(page)
    return true
  }

  const preserveCallbackFalse = (page: Page) => {
    alert(page)
    return false
  }

  window._luna_page_key = useId()

  return (
    <div>
      <span className="text">This is the links page that demonstrates preserve state on Links</span>
      <span className="foo">Foo is now {foo}</span>
      <label>
        Example Field
        <input type="text" name="example-field" className="field" />
      </label>

      <Link href="/links/preserve-state-page-two" preserveState data={{ foo: 'bar' }} className="preserve">
        [State] Preserve: true
      </Link>
      <Link
        href="/links/preserve-state-page-two"
        preserveState={false}
        data={{ foo: 'baz' }}
        className="preserve-false"
      >
        [State] Preserve: false
      </Link>

      <Link
        href="/links/preserve-state-page-two"
        preserveState={preserveCallback}
        data={{ foo: 'callback-bar' }}
        className="preserve-callback"
      >
        [State] Preserve Callback: true
      </Link>
      <Link
        href="/links/preserve-state-page-two"
        preserveState={preserveCallbackFalse}
        data={{ foo: 'callback-baz' }}
        className="preserve-callback-false"
      >
        [State] Preserve Callback: false
      </Link>
    </div>
  )
}

PreserveState.layout = (page: React.ReactNode) => <WithoutScrollRegion children={page} />

export default PreserveState

// packages/vue3/test-app/Pages/Links/PreserveState.vue
<script setup lang="ts">
import type { Page } from '@laraxgram/luna'
import { Link } from '@laraxgram/vue3'
import { getCurrentInstance, onMounted } from 'vue'
import WithoutScrollRegion from '../../Layouts/WithoutScrollRegion.vue'

defineOptions({
  layout: WithoutScrollRegion,
})

defineProps({
  foo: {
    type: String,
    default: 'default',
  },
})

const preserveCallback = (page: Page) => {
  alert(page)

  return true
}

const preserveCallbackFalse = (page: Page) => {
  alert(page)

  return false
}

onMounted(() => {
  window._luna_page_key = getCurrentInstance()?.uid
})
</script>

<template>
  <div>
    <span class="text">This is the links page that demonstrates preserve state on Links</span>
    <span class="foo">Foo is now {{ foo }}</span>
    <label>
      Example Field
      <input type="text" name="example-field" class="field" />
    </label>

    <Link href="/links/preserve-state-page-two" preserve-state :data="{ foo: 'bar' }" class="preserve"
      >[State] Preserve: true</Link
    >
    <Link href="/links/preserve-state-page-two" :preserve-state="false" :data="{ foo: 'baz' }" class="preserve-false"
      >[State] Preserve: false</Link
    >

    <Link
      href="/links/preserve-state-page-two"
      :preserve-state="preserveCallback"
      :data="{ foo: 'callback-bar' }"
      class="preserve-callback"
      >[State] Preserve Callback: true</Link
    >
    <Link
      href="/links/preserve-state-page-two"
      :preserve-state="preserveCallbackFalse"
      :data="{ foo: 'callback-baz' }"
      class="preserve-callback-false"
      >[State] Preserve Callback: false</Link
    >
  </div>
</template>
