// packages/react/test-app/Pages/Links/ScrollRegionList.tsx
import { VisitHelperOptions } from '@lunajs/core'
import { router } from '@lunajs/react'
import WithScrollRegion from '@/Layouts/WithScrollRegion.jsx'

const ScrollRegionList = ({ user_id }: { user_id?: number }) => {
  const navigate = (id: number, options: VisitHelperOptions = {}) => {
    router.get(`/links/scroll-region-list/user/${id}`, {}, options)
  }

  const users = Array.from({ length: 10 }, (_, i) => ({ id: i + 1, name: `User ${i + 1}` }))

  return (
    <div>
      <span className="text">Scrollable list with scroll region</span>
      <div className="user-text">Clicked user: {user_id || 'none'}</div>

      {users.map((user) => (
        <div key={user.id} style={{ padding: '20px', borderBottom: '1px solid #ccc' }}>
          <div style={{ marginBottom: '10px', width: '500px' }}>{user.name}</div>
          <button onClick={() => navigate(user.id)}>Default</button>
          <button onClick={() => navigate(user.id, { preserveScroll: true })}>Preserve True</button>
          <button onClick={() => navigate(user.id, { preserveScroll: false })}>Preserve False</button>
        </div>
      ))}
    </div>
  )
}

ScrollRegionList.layout = (page: React.ReactNode) => <WithScrollRegion children={page} />

export default ScrollRegionList

// packages/vue3/test-app/Pages/Links/ScrollRegionList.vue
<script setup lang="ts">
import { VisitHelperOptions } from '@lunajs/core'
import { router } from '@lunajs/vue3'
import WithScrollRegion from '@/Layouts/WithScrollRegion.vue'

defineProps({
  user_id: Number,
})

const navigate = (id: number, options: VisitHelperOptions = {}) => {
  router.get(`/links/scroll-region-list/user/${id}`, {}, options)
}

const users = Array.from({ length: 10 }, (_, i) => ({ id: i + 1, name: `User ${i + 1}` }))
</script>

<template>
  <WithScrollRegion>
    <div>
      <span class="text">Scrollable list with scroll region</span>
      <div class="user-text">Clicked user: {{ user_id || 'none' }}</div>

      <div v-for="user in users" :key="user.id" style="padding: 20px; border-bottom: 1px solid #ccc">
        <div style="margin-bottom: 10px; width: 500px">{{ user.name }}</div>
        <button @click="navigate(user.id)">Default</button>
        <button @click="navigate(user.id, { preserveScroll: true })">Preserve True</button>
        <button @click="navigate(user.id, { preserveScroll: false })">Preserve False</button>
      </div>
    </div>
  </WithScrollRegion>
</template>
