// packages/vue3/test-app/Pages/FormComponent/TypeScript/Context.vue
<!-- This component is used for checking the TypeScript implementation; there is no Playwright test depending on it. -->
<script setup lang="ts">
import { useFormContext } from '@lunajs/vue3'

interface UserForm {
  name: string
  email: string
}

const form = useFormContext<UserForm>()

if (form) {
  form.clearErrors('name')
  form.reset('email')
  form.setError('name', 'Error')

  // @ts-expect-error - 'invalid_field' should not be a valid key
  form.clearErrors('invalid_field')

  const data = form.getData()
  console.log(data.name, data.email)

  // @ts-expect-error - 'invalid_field' should not be a valid key
  console.log(data.invalid_field)
}
</script>

<template>
  <div>Context component</div>
</template>

// packages/react/test-app/Pages/FormComponent/TypeScript/Context.tsx
// This component is used for checking the TypeScript implementation; there is no Playwright test depending on it.
import { useFormContext } from '@lunajs/react'

interface UserForm {
  name: string
  email: string
}

export default () => {
  const form = useFormContext<UserForm>()

  if (!form) {
    return null
  }

  form.clearErrors('name')
  form.reset('email')
  form.setError('name', 'Error')

  // @ts-expect-error - 'invalid_field' should not be a valid key
  form.clearErrors('invalid_field')

  const data = form.getData()
  console.log(data.name, data.email)

  // @ts-expect-error - 'invalid_field' should not be a valid key
  console.log(data.invalid_field)

  return <div>Context component</div>
}
