// packages/vue3/test-app/Pages/FormComponent/TypeScript/Ref.vue
<!-- This component is used for checking the TypeScript implementation; there is no Playwright test depending on it. -->
<script setup lang="ts">
import { FormComponentRef } from '@lunajs/core'
import { Form } from '@lunajs/vue3'
import { ref } from 'vue'

interface UserForm {
  name: string
  email: string
}

const formRef = ref<FormComponentRef<UserForm> | null>(null)
</script>

<template>
  <div>
    <Form ref="formRef" action="/users" method="post">
      <input name="name" />
      <input name="email" />
      <button type="submit">Submit</button>
    </Form>

    <button @click="formRef?.clearErrors('name')">Clear name error</button>
    <button @click="formRef?.reset('email')">Reset email</button>

    <!-- @vue-expect-error - 'invalid_field' should not be a valid key -->
    <button @click="formRef?.clearErrors('invalid_field')">Invalid</button>
  </div>
</template>

// packages/react/test-app/Pages/FormComponent/TypeScript/Ref.tsx
// This component is used for checking the TypeScript implementation; there is no Playwright test depending on it.
import { FormComponentRef } from '@lunajs/core'
import { Form } from '@lunajs/react'
import { useRef } from 'react'

interface UserForm {
  name: string
  email: string
}

export default () => {
  const formRef = useRef<FormComponentRef<UserForm>>(null)

  return (
    <div>
      <Form<UserForm> action="/users" method="post" ref={formRef}>
        <input name="name" />
        <input name="email" />
        <button type="submit">Submit</button>
      </Form>

      <button onClick={() => formRef.current?.clearErrors('name')}>Clear name error</button>
      <button onClick={() => formRef.current?.reset('email')}>Reset email</button>

      {/* @ts-expect-error - 'invalid_field' should not be a valid key */}
      <button onClick={() => formRef.current?.clearErrors('invalid_field')}>Invalid</button>
    </div>
  )
}
