// packages/vue3/test-app/Pages/FormHelper/Precognition/WithAllErrorsConfig.vue
<script setup lang="ts">
import { config, useForm } from '@lunajs/vue3'

// Set global config for withAllErrors (no .withAllErrors() call on the form)
config.set('form.withAllErrors', true)

const form = useForm({
  name: '',
  email: '',
})
  .withPrecognition('post', '/precognition/with-all-errors')
  .setValidationTimeout(100)
</script>

<template>
  <div>
    <div>
      <input v-model="form.name" name="name" placeholder="Name" @blur="form.validate('name')" />
      <div v-if="form.invalid('name')">
        <template v-if="Array.isArray(form.errors.name)">
          <p v-for="(error, index) in form.errors.name" :key="index" :id="`name-error-${index}`">
            {{ error }}
          </p>
        </template>
        <p v-else id="name-error-0">{{ form.errors.name }}</p>
      </div>
      <p v-if="form.valid('name')">Name is valid!</p>
    </div>

    <div>
      <input v-model="form.email" name="email" placeholder="Email" @blur="form.validate('email')" />
      <div v-if="form.invalid('email')">
        <template v-if="Array.isArray(form.errors.email)">
          <p v-for="(error, index) in form.errors.email" :key="index" :id="`email-error-${index}`">
            {{ error }}
          </p>
        </template>
        <p v-else id="email-error-0">{{ form.errors.email }}</p>
      </div>
      <p v-if="form.valid('email')">Email is valid!</p>
    </div>

    <p v-if="form.validating">Validating...</p>
  </div>
</template>

// packages/svelte/test-app/Pages/FormHelper/Precognition/WithAllErrorsConfig.svelte
<script lang="ts">
  import { config, useForm } from '@lunajs/svelte'

  // Set global config for withAllErrors (no .withAllErrors() call on the form)
  config.set('form.withAllErrors', true)

  const form = useForm({
    name: '',
    email: '',
  })
    .withPrecognition('post', '/precognition/with-all-errors')
    .setValidationTimeout(100)
</script>

<div>
  <div>
    <input bind:value={form.name} name="name" placeholder="Name" onblur={() => form.validate('name')} />
    {#if form.invalid('name')}
      <div>
        {#if Array.isArray(form.errors.name)}
          {#each form.errors.name as error, index (index)}
            <p id="name-error-{index}">{error}</p>
          {/each}
        {:else}
          <p id="name-error-0">{form.errors.name}</p>
        {/if}
      </div>
    {/if}
    {#if form.valid('name')}<p>Name is valid!</p>{/if}
  </div>

  <div>
    <input bind:value={form.email} name="email" placeholder="Email" onblur={() => form.validate('email')} />
    {#if form.invalid('email')}
      <div>
        {#if Array.isArray(form.errors.email)}
          {#each form.errors.email as error, index (index)}
            <p id="email-error-{index}">{error}</p>
          {/each}
        {:else}
          <p id="email-error-0">{form.errors.email}</p>
        {/if}
      </div>
    {/if}
    {#if form.valid('email')}<p>Email is valid!</p>{/if}
  </div>

  {#if form.validating}<p>Validating...</p>{/if}
</div>
