// packages/react/src/Deferred.ts
import { isSameUrlWithoutQueryOrHash, partialReloadRequestsSomeProps } from '@laraxgram/luna'
import { get } from 'es-toolkit/compat'
import { ReactNode, useEffect, useMemo, useRef, useState } from 'react'
import { router } from '.'
import usePage from './usePage'

interface DeferredSlotProps {
  reloading: boolean
}

interface DeferredProps {
  children: ReactNode | ((props: DeferredSlotProps) => ReactNode)
  rescue?: ReactNode | ((props: DeferredSlotProps) => ReactNode)
  fallback: ReactNode | (() => ReactNode)
  data: string | string[]
}

const Deferred = ({ children, data, rescue, fallback }: DeferredProps) => {
  if (!data) {
    throw new Error('`<Deferred>` requires a `data` prop to be a string or array of strings')
  }

  if (!fallback) {
    throw new Error('`<Deferred>` requires a `fallback` prop')
  }

  const [reloading, setReloading] = useState(false)
  const activeReloads = useRef(new Set<object>())
  const page = usePage()
  const pageProps = page.props
  const keys = useMemo(() => (Array.isArray(data) ? data : [data]), [data])
  const rescuedKeys = useMemo(() => new Set(page.rescuedProps), [page.rescuedProps])

  useEffect(() => {
    const removeStartListener = router.on('start', (e) => {
      const visit = e.detail.visit

      if (
        visit.preserveState === true &&
        isSameUrlWithoutQueryOrHash(visit.url, window.location) &&
        partialReloadRequestsSomeProps(visit, keys)
      ) {
        activeReloads.current.add(visit)
        setReloading(true)
      }
    })

    const removeFinishListener = router.on('finish', (e) => {
      const visit = e.detail.visit

      if (activeReloads.current.has(visit)) {
        activeReloads.current.delete(visit)
        setReloading(activeReloads.current.size > 0)
      }
    })

    return () => {
      removeStartListener()
      removeFinishListener()
      activeReloads.current.clear()
    }
  }, [keys])

  const propsAreDefined = useMemo(() => keys.every((key) => get(pageProps, key) !== undefined), [keys, pageProps])
  const hasRescuedProps = useMemo(() => keys.some((key) => rescuedKeys.has(key)), [keys, rescuedKeys])

  if (propsAreDefined && !hasRescuedProps) {
    if (typeof children === 'function') {
      return children({ reloading })
    }

    return children
  }

  if (hasRescuedProps && rescue) {
    return typeof rescue === 'function' ? rescue({ reloading }) : rescue
  }

  return typeof fallback === 'function' ? fallback() : fallback
}

Deferred.displayName = 'LunaDeferred'

export default Deferred

// packages/svelte/src/components/Deferred.svelte
<script lang="ts">
  import { isSameUrlWithoutQueryOrHash, router, partialReloadRequestsSomeProps } from '@laraxgram/luna'
  import { get } from 'es-toolkit/compat'
  import { page } from '../index'

  interface Props {
    data: string | string[]
    rescue?: import('svelte').Snippet<[{ reloading: boolean }]>
    fallback?: import('svelte').Snippet
    children?: import('svelte').Snippet<[{ reloading: boolean }]>
  }

  let { data, rescue, fallback, children }: Props = $props()

  const keys = $derived(Array.isArray(data) ? data : [data])
  const rescuedKeys = $derived(new Set(page.rescuedProps))
  const loaded = $derived(keys.every((key) => typeof get(page.props, key) !== 'undefined'))
  const failed = $derived(keys.some((key) => rescuedKeys.has(key)))

  let reloading = $state(false)
  const activeReloads = new Set<object>()

  $effect(() => {
    const removeStartListener = router.on('start', (e) => {
      const visit = e.detail.visit

      if (
        visit.preserveState === true &&
        isSameUrlWithoutQueryOrHash(visit.url, window.location) &&
        partialReloadRequestsSomeProps(visit, keys)
      ) {
        activeReloads.add(visit)
        reloading = true
      }
    })

    const removeFinishListener = router.on('finish', (e) => {
      const visit = e.detail.visit

      if (activeReloads.has(visit)) {
        activeReloads.delete(visit)
        reloading = activeReloads.size > 0
      }
    })

    return () => {
      removeStartListener()
      removeFinishListener()
      activeReloads.clear()
    }
  })

  $effect.pre(() => {
    if (!fallback) {
      throw new Error('`<Deferred>` requires a `fallback` snippet')
    }
  })
</script>

{#if loaded && !failed}
  {@render children?.({ reloading })}
{:else if failed && rescue}
  {@render rescue?.({ reloading })}
{:else}
  {@render fallback?.()}
{/if}
