// packages/react/src/WhenVisible.ts
import { ReloadOptions, router } from '@lunajs/core'
import { get } from 'es-toolkit/compat'
import { createElement, ReactNode, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import usePage from './usePage'

interface WhenVisibleSlotProps {
  fetching: boolean
}

interface WhenVisibleProps {
  children: ReactNode | ((props: WhenVisibleSlotProps) => ReactNode)
  fallback: ReactNode | (() => ReactNode)
  data?: string | string[]
  params?: ReloadOptions
  buffer?: number
  as?: string
  always?: boolean
}

const WhenVisible = ({ children, data, params, buffer, as, always, fallback }: WhenVisibleProps) => {
  always = always ?? false
  as = as ?? 'div'
  fallback = fallback ?? null

  const pageProps = usePage().props
  const keys = useMemo(() => (data ? (Array.isArray(data) ? data : [data]) : []), [data])

  const [loaded, setLoaded] = useState(() => keys.length > 0 && keys.every((key) => get(pageProps, key) !== undefined))
  const [isFetching, setIsFetching] = useState(false)
  const fetching = useRef<boolean>(false)
  const ref = useRef<HTMLDivElement>(null)
  const observer = useRef<IntersectionObserver | null>(null)
  const getReloadParamsRef = useRef<() => Partial<ReloadOptions>>(() => ({}))

  useEffect(() => {
    if (keys.length > 0) {
      setLoaded(keys.every((key) => get(pageProps, key) !== undefined))
    }
  }, [pageProps, keys])

  const getReloadParams = useCallback<() => Partial<ReloadOptions>>(() => {
    const reloadParams: Partial<ReloadOptions> = { preserveErrors: true, ...params }

    if (data) {
      reloadParams.only = (Array.isArray(data) ? data : [data]) as string[]
    }

    return reloadParams
  }, [params, data])

  getReloadParamsRef.current = getReloadParams

  const registerObserver = () => {
    observer.current?.disconnect()

    observer.current = new IntersectionObserver(
      (entries) => {
        if (!entries[0].isIntersecting) {
          return
        }

        if (fetching.current) {
          return
        }

        if (!always && loaded) {
          return
        }

        fetching.current = true
        setIsFetching(true)

        const reloadParams = getReloadParamsRef.current()

        router.reload({
          ...reloadParams,
          onStart: (e) => {
            fetching.current = true
            setIsFetching(true)
            reloadParams.onStart?.(e)
          },
          onFinish: (e) => {
            setLoaded(true)
            fetching.current = false
            setIsFetching(false)
            reloadParams.onFinish?.(e)

            if (!always) {
              observer.current?.disconnect()
            }
          },
        })
      },
      {
        rootMargin: `${buffer || 0}px`,
      },
    )

    observer.current.observe(ref.current!)
  }

  useEffect(() => {
    if (!ref.current) {
      return
    }

    if (loaded && !always) {
      return
    }

    registerObserver()

    return () => {
      observer.current?.disconnect()
    }
  }, [always, loaded, buffer])

  const resolveChildren = () => (typeof children === 'function' ? children({ fetching: isFetching }) : children)
  const resolveFallback = () => (typeof fallback === 'function' ? fallback() : fallback)

  if (always || !loaded) {
    return createElement(
      as,
      {
        props: null,
        ref,
      },
      loaded ? resolveChildren() : resolveFallback(),
    )
  }

  return loaded ? resolveChildren() : null
}

WhenVisible.displayName = 'LunaWhenVisible'

export default WhenVisible

// packages/svelte/src/components/WhenVisible.svelte
<script lang="ts">
  import { router, type ReloadOptions } from '@lunajs/core'
  import { get } from 'es-toolkit/compat'
  import { usePage } from '../page.svelte'

  interface Props {
    data?: string | string[]
    params?: ReloadOptions
    buffer?: number
    as?: keyof HTMLElementTagNameMap
    always?: boolean
    children?: import('svelte').Snippet<[any]>
    fallback?: import('svelte').Snippet
  }

  let { data = '', params = {}, buffer = 0, as = 'div', always = false, children, fallback }: Props = $props()

  let keys = $derived(data ? (Array.isArray(data) ? data : [data]) : [])
  let loaded = $derived(keys.length > 0 && keys.every((key) => get(page.props, key) !== undefined))
  let fetching = $state(false)
  let observer: IntersectionObserver | null = null

  const page = usePage()

  function attachObserver(el: HTMLElement) {
    observer = new IntersectionObserver(
      (entries) => {
        if (!entries[0].isIntersecting) {
          return
        }

        if (fetching) {
          return
        }

        if (!always && loaded) {
          return
        }

        fetching = true

        const reloadParams = getReloadParams()

        router.reload({
          ...reloadParams,
          onStart: (event) => {
            fetching = true
            reloadParams.onStart?.(event)
          },
          onFinish: (event) => {
            loaded = true
            fetching = false
            reloadParams.onFinish?.(event)

            if (!always) {
              observer?.disconnect()
            }
          },
        })
      },
      {
        rootMargin: `${buffer}px`,
      },
    )

    observer.observe(el)

    // Clean up will run like onDestroy
    return () => {
      observer?.disconnect()
    }
  }

  function getReloadParams(): Partial<ReloadOptions> {
    const reloadParams: Partial<ReloadOptions> = { preserveErrors: true, ...params }

    if (data !== '') {
      reloadParams.only = (Array.isArray(data) ? data : [data]) as string[]
    }

    return reloadParams
  }
</script>

{#if always || !loaded}
  <svelte:element this={as} {@attach attachObserver} />
{/if}

{#if loaded}
  {@render children?.({ fetching })}
{:else if fallback}
  {@render fallback?.()}
{/if}
