// packages/svelte/test-app/Pages/FormHelper/TypeScript/WrapperChild.svelte
<!-- eslint-disable @typescript-eslint/no-explicit-any -->
<script lang="ts" generics="T extends Record<string, any>">
  import { useForm, type LunaForm } from '@laraxgram/svelte'
  import type { Snippet } from 'svelte'

  let { data, children }: { data: T; children: Snippet<[LunaForm<T>]> } = $props()

  // svelte-ignore state_referenced_locally
  const form = useForm(data)
</script>

<form>
  {@render children(form)}
</form>

// packages/vue3/test-app/Pages/FormHelper/TypeScript/WrapperChild.vue
<!-- eslint-disable @typescript-eslint/no-explicit-any -->
<script setup lang="ts" generic="T extends Record<string, any>">
import { useForm } from '@laraxgram/vue3'

const props = defineProps<{ data: T }>()

const form = useForm(props.data)
</script>

<template>
  <form>
    <slot :form="form" />
  </form>
</template>
