// packages/svelte/test-app/Layouts/NestedLayout.svelte
<script lang="ts">
  import { page } from '@lunajs/svelte'
  import { onMount } from 'svelte'
  interface Props {
    children?: import('svelte').Snippet
  }

  let { children }: Props = $props()
  let createdAt = $state<number | null>(null)

  onMount(() => {
    window._luna_nested_layout_id = crypto.randomUUID()
    createdAt = Date.now()
  })

  // Update props reactively when page changes
  $effect(() => {
    if (typeof window !== 'undefined') {
      window._luna_nested_layout_props = page.props
    }
  })
</script>

<div>
  <span>Nested Layout</span>
  <span>{createdAt}</span>
  <div>
    {@render children?.()}
  </div>
</div>

// packages/react/test-app/Layouts/NestedLayout.tsx
import { usePage } from '@lunajs/react'
import { useId, useState } from 'react'

export default ({ children }: { children: React.ReactNode }) => {
  const [createdAt] = useState(Date.now())

  window._luna_nested_layout_id = useId()
  window._luna_nested_layout_props = usePage().props

  return (
    <div>
      <span>Nested Layout</span>
      <span>{createdAt}</span>
      <div>{children}</div>
    </div>
  )
}
