// packages/vue3/test-app/Layouts/NestedLayout.vue
<script setup lang="ts">
import { usePage } from '@lunajs/vue3'
import { getCurrentInstance, onMounted, ref } from 'vue'

const createdAt = ref<number | null>(null)

onMounted(() => {
  window._luna_nested_layout_id = getCurrentInstance()?.uid
  window._luna_nested_layout_props = usePage().props
  createdAt.value = Date.now()
})
</script>

<template>
  <div>
    <span>Nested Layout</span>
    <span>{{ createdAt }}</span>
    <div>
      <slot />
    </div>
  </div>
</template>

// packages/react/test-app/Layouts/NestedLayout.tsx
import { usePage } from '@lunajs/react'
import { useId, useState } from 'react'

export default ({ children }: { children: React.ReactNode }) => {
  const [createdAt] = useState(Date.now())

  window._luna_nested_layout_id = useId()
  window._luna_nested_layout_props = usePage().props

  return (
    <div>
      <span>Nested Layout</span>
      <span>{createdAt}</span>
      <div>{children}</div>
    </div>
  )
}
