// packages/vue3/test-app/Pages/Links/Reactivity.vue
<script setup lang="ts">
import { CacheForOption, LinkPrefetchOption, Method } from '@lunajs/core'
import { Link } from '@lunajs/vue3'
import { ref } from 'vue'

const method = ref<Method>('get')
const href = ref('/dump/get')
const data = ref({ foo: 'bar' })
const headers = ref({ 'X-Custom-Header': 'value' })
const prefetch = ref<boolean | LinkPrefetchOption>(false)
const cacheFor = ref<CacheForOption>(0)

const change = () => {
  method.value = 'post'
  href.value = '/dump/post'
  data.value = { foo: 'baz' }
  headers.value = { 'X-Custom-Header': 'new-value' }
}

const enablePrefetch = () => {
  prefetch.value = 'hover'
  cacheFor.value = '1s'
}
</script>

<template>
  <div>
    <span class="text">
      This page demonstrates reactivity in Luna links. Click the button to change the link properties.
    </span>

    <Link :method="method" :href="href" :data="data" :headers="headers">Submit</Link>
    <button @click="change">Change Link props</button>

    <Link href="/dump/get" :prefetch="prefetch" :cache-for="cacheFor"> Prefetch Link </Link>

    <button @click="enablePrefetch">Enable Prefetch (1s cache)</button>
  </div>
</template>

// packages/svelte/test-app/Pages/Links/Reactivity.svelte
<script lang="ts">
  import type { CacheForOption, LinkPrefetchOption, Method } from '@lunajs/core'
  import { Link } from '@lunajs/svelte'

  let method: Method = $state('get')
  let href = $state('/dump/get')
  let data = $state({ foo: 'bar' })
  let headers = $state({ 'X-Custom-Header': 'value' })
  let prefetch: boolean | LinkPrefetchOption = $state(false)
  let cacheFor: CacheForOption = $state(0)

  function change() {
    method = 'post'
    href = '/dump/post'
    data = { foo: 'baz' }
    headers = { 'X-Custom-Header': 'new-value' }
  }

  function enablePrefetch() {
    prefetch = 'hover'
    cacheFor = '1s'
  }
</script>

<div>
  <span class="text">
    This page demonstrates reactivity in Luna links. Click the button to change the link properties.
  </span>

  <Link {method} {href} {data} {headers}>Submit</Link>

  <button onclick={change}>Change Link Props</button>

  <Link href="/dump/get" {prefetch} {cacheFor}>Prefetch Link</Link>

  <button onclick={enablePrefetch}>Enable Prefetch (1s cache)</button>
</div>
