// packages/react/test-app/Pages/ClientSideVisit/Page1.tsx
import { Page } from '@laraxgram/luna'
import { router } from '@laraxgram/react'
import { useState } from 'react'

interface PageProps {
  foo: string
  bar: string
}

export default ({ foo, bar }: PageProps) => {
  const [errors, setErrors] = useState(0)
  const [finished, setFinished] = useState(0)
  const [success, setSuccess] = useState(0)
  const [random] = useState(Math.random())

  const bagErrors = () => {
    router.replace({
      preserveState: true,
      props: (props: Page['props']) => ({ ...props, errors: { bag: { foo: 'bar' } } }),
      errorBag: 'bag',
      onError: (err) => {
        setErrors(Object.keys(err).length)
      },
      onFinish: () => setFinished(finished + 1),
      onSuccess: () => setSuccess(success + 1),
    })
  }

  const defaultErrors = () => {
    router.replace({
      preserveState: true,
      props: (props: PageProps) => ({ ...props, errors: { foo: 'bar', baz: 'qux' } }),
      onError: (err) => {
        setErrors(Object.keys(err).length)
      },
      onFinish: () => setFinished(finished + 1),
      onSuccess: () => setSuccess(success + 1),
    })
  }

  const replace = () => {
    router.replace({
      preserveState: true,
      props: (props) => ({ ...props, foo: 'foo from client' }),
      onFinish: () => setFinished(finished + 1),
      onSuccess: () => setSuccess(success + 1),
    })
  }

  const replaceAndPreserveStateWithErrors = (errors = {}) => {
    router.replace({
      preserveState: 'errors',
      props: (props: PageProps) => ({ ...props, errors }),
    })
  }

  const push = () => {
    router.push({
      url: '/client-side-visit-2',
      component: 'ClientSideVisit/Page2',
      props: { baz: 'baz from client' },
    })
  }

  const pushSameUrl = () => {
    router.push({
      url: '/client-side-visit',
      component: 'ClientSideVisit/Page1',
      props: (props: PageProps) => ({ ...props, foo: 'foo from client' }),
    })
  }

  return (
    <div>
      <div>{foo}</div>
      <div>{bar}</div>
      <button onClick={replace}>Replace</button>
      <button onClick={() => replaceAndPreserveStateWithErrors({ name: 'Field is required' })}>
        Replace with errors
      </button>
      <button onClick={() => replaceAndPreserveStateWithErrors()}>Replace without errors</button>
      <button onClick={push}>Push</button>
      <button onClick={pushSameUrl}>Push same URL</button>
      <button onClick={defaultErrors}>Errors (default)</button>
      <button onClick={bagErrors}>Errors (bag)</button>
      <div>Errors: {errors}</div>
      <div>Finished: {finished}</div>
      <div>Success: {success}</div>
      <div id="random">Random: {random}</div>
    </div>
  )
}

// packages/vue3/test-app/Pages/ClientSideVisit/Page1.vue
<script setup lang="ts">
import { Page } from '@laraxgram/luna'
import { router } from '@laraxgram/vue3'
import { ref } from 'vue'

interface PageProps {
  foo: string
  bar: string
}

defineProps<PageProps>()

const errors = ref(0)
const finished = ref(0)
const success = ref(0)
const random = ref(Math.random())

const bagErrors = () => {
  router.replace({
    preserveState: true,
    props: (props: Page['props']) => ({ ...props, errors: { bag: { foo: 'bar' } } }),
    errorBag: 'bag',
    onError: (err) => {
      errors.value = Object.keys(err).length
    },
    onFinish: () => finished.value++,
    onSuccess: () => success.value++,
  })
}

const defaultErrors = () => {
  router.replace({
    preserveState: true,
    props: (props: PageProps) => ({ ...props, errors: { foo: 'bar', baz: 'qux' } }),
    onError: (err) => {
      errors.value = Object.keys(err).length
    },
    onFinish: () => finished.value++,
    onSuccess: () => success.value++,
  })
}

const replace = () => {
  router.replace({
    preserveState: true,
    props: (props) => ({ ...props, foo: 'foo from client' }),
    onFinish: (visit) => {
      if (visit.preserveState) {
        finished.value++
      }
    },
    onSuccess: (page) => {
      if (page.props.foo === 'foo from client') {
        success.value++
      }
    },
  })
}

const replaceAndPreserveStateWithErrors = (errors = {}) => {
  router.replace({
    preserveState: 'errors',
    props: (props: PageProps) => ({ ...props, errors }),
  })
}

const push = () => {
  router.push({
    url: '/client-side-visit-2',
    component: 'ClientSideVisit/Page2',
    props: {
      baz: 'baz from client',
    },
  })
}

const pushSameUrl = () => {
  router.push({
    url: '/client-side-visit',
    component: 'ClientSideVisit/Page1',
    props: (props: PageProps) => ({ ...props, foo: 'foo from client' }),
  })
}
</script>

<template>
  <div>{{ foo }}</div>
  <div>{{ bar }}</div>
  <button @click="replace">Replace</button>
  <button @click="() => replaceAndPreserveStateWithErrors({ name: 'Field is required' })">Replace with errors</button>
  <button @click="() => replaceAndPreserveStateWithErrors()">Replace without errors</button>
  <button @click="push">Push</button>
  <button @click="pushSameUrl">Push same URL</button>
  <button @click="defaultErrors">Errors (default)</button>
  <button @click="bagErrors">Errors (bag)</button>
  <div>Errors: {{ errors }}</div>
  <div>Finished: {{ finished }}</div>
  <div>Success: {{ success }}</div>
  <div id="random">Random: {{ random }}</div>
</template>
