// packages/svelte/test-app/Pages/FormHelper/TypeScript/Parent.svelte
<script lang="ts">
  // This component is used for checking the TypeScript implementation; there is no Playwright test depending on it.
  import { useForm } from '@laraxgram/svelte'
  import Child from './Child.svelte'

  const form = useForm({
    name: 'foo',
    remember: false,
  })
</script>

<Child {form} />

// packages/react/test-app/Pages/FormHelper/TypeScript/Parent.tsx
// This component is used for checking the TypeScript implementation; there is no Playwright test depending on it.
import { useForm } from '@laraxgram/react'
import Child from './Child'

export default function Parent() {
  const form = useForm({
    name: 'foo',
    remember: false,
  })

  return (
    <div>
      <Child form={form} />
    </div>
  )
}
