// packages/svelte/test-app/Pages/InfiniteScroll/ReloadUnrelated.svelte
<script lang="ts">
  import { InfiniteScroll, router } from '@lunajs/svelte'
  import UserCard, { type User } from './UserCard.svelte'

  interface Props {
    users: { data: User[] }
    time: number
  }

  let { users, time }: Props = $props()

  const reloadTime = () => {
    router.reload({ only: ['time'] })
  }
</script>

<div>
  <div>
    <button onclick={reloadTime} id="reload-button">Reload Time</button>
    <span id="time-display">Current time: {time}</span>
  </div>

  <InfiniteScroll data="users">
    {#each users.data as user (user.id)}
      <UserCard {user} />
    {/each}
  </InfiniteScroll>
</div>

// packages/react/test-app/Pages/InfiniteScroll/ReloadUnrelated.tsx
import { InfiniteScroll, router } from '@lunajs/react'
import UserCard, { User } from './UserCard'

export default ({ users, time }: { users: { data: User[] }; time: number }) => {
  const reloadTime = () => {
    router.reload({ only: ['time'] })
  }

  return (
    <div>
      <div>
        <button onClick={reloadTime} id="reload-button">
          Reload Time
        </button>
        <span id="time-display"> Current time: {time}</span>
      </div>

      <InfiniteScroll data="users">
        {users.data.map((user) => (
          <UserCard key={user.id} user={user} />
        ))}
      </InfiniteScroll>
    </div>
  )
}
