// packages/vue3/test-app/Pages/Flash/Partial.vue
<script setup lang="ts">
import { router, usePage } from '@lunajs/vue3'
import { ref } from 'vue'

defineProps<{
  count: number
}>()

const page = usePage()
const flashEventCount = ref(0)

router.on('flash', () => {
  flashEventCount.value++
})

const reloadWithSameFlash = () => {
  router.reload({ only: ['count'], data: { flashType: 'same', count: Date.now() } })
}

const reloadWithDifferentFlash = () => {
  router.reload({ only: ['count'], data: { flashType: 'different', count: Date.now() } })
}

const reloadWithoutFlash = () => {
  router.reload({ only: ['count'], data: { flashType: 'none', count: Date.now() } })
}
</script>

<template>
  <div>
    <span id="flash">{{ JSON.stringify(page.flash) }}</span>
    <span id="flash-event-count">{{ flashEventCount }}</span>
    <span id="count">{{ count }}</span>

    <button @click="reloadWithSameFlash">Reload with same flash</button>
    <button @click="reloadWithDifferentFlash">Reload with different flash</button>
    <button @click="reloadWithoutFlash">Reload without flash</button>
  </div>
</template>

// packages/svelte/test-app/Pages/Flash/Partial.svelte
<script lang="ts">
  import { page, router } from '@lunajs/svelte'

  interface Props {
    count: number
  }

  let { count }: Props = $props()

  let flashEventCount = $state(0)

  router.on('flash', () => {
    flashEventCount++
  })

  const reloadWithSameFlash = () => {
    router.reload({ only: ['count'], data: { flashType: 'same', count: Date.now() } })
  }

  const reloadWithDifferentFlash = () => {
    router.reload({ only: ['count'], data: { flashType: 'different', count: Date.now() } })
  }

  const reloadWithoutFlash = () => {
    router.reload({ only: ['count'], data: { flashType: 'none', count: Date.now() } })
  }
</script>

<div>
  <span id="flash">{JSON.stringify(page.flash)}</span>
  <span id="flash-event-count">{flashEventCount}</span>
  <span id="count">{count}</span>

  <button onclick={reloadWithSameFlash}>Reload with same flash</button>
  <button onclick={reloadWithDifferentFlash}>Reload with different flash</button>
  <button onclick={reloadWithoutFlash}>Reload without flash</button>
</div>
