// packages/react/test-app/Pages/InfiniteScroll/Filtering.tsx
import { InfiniteScroll, Link, useForm } from '@laraxgram/react'
import { debounce } from 'es-toolkit'
import { useEffect, useMemo } from 'react'
import UserCard, { User } from './UserCard'

interface Props {
  users: { data: User[] }
  preserveState: boolean
  filter?: string
  search?: string
}

export default ({ users, preserveState, filter, search }: Props) => {
  const { data, setData, get } = useForm({
    filter: undefined,
    page: undefined,
    search: search,
  })

  const debouncedSearch = useMemo(
    () =>
      debounce(() => {
        get(
          '',
          preserveState
            ? {
                preserveState: true,
                replace: true,
                only: ['users', 'search', 'filter'],
                reset: ['users'],
              }
            : {
                replace: true,
              },
        )
      }, 250),
    [get, preserveState],
  )

  useEffect(() => {
    if (data.search !== search) {
      debouncedSearch()
    }

    return () => {
      debouncedSearch.cancel?.()
    }
  }, [data.search, search, debouncedSearch])

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setData('search', e.target.value)
  }

  return (
    <div>
      <div style={{ marginBottom: '20px', display: 'flex', gap: '10px' }}>
        <Link href="">No Filter</Link>
        <Link href="?filter=a-m">A-M</Link>
        <Link href="?filter=n-z">N-Z</Link>
        <div>Current filter: {filter || 'none'}</div>
        <div>Current search: {search || 'none'}</div>
        <input value={data.search || ''} onChange={handleSearchChange} placeholder="Search..." />
      </div>

      <InfiniteScroll
        data="users"
        style={{ display: 'grid', gap: '20px' }}
        loading={() => <div style={{ textAlign: 'center', padding: '20px' }}>Loading...</div>}
      >
        {users.data.map((user) => (
          <UserCard key={user.id} user={user} />
        ))}
      </InfiniteScroll>

      <div style={{ marginTop: '20px', display: 'flex', gap: '10px' }}>
        <Link href="">No Filter</Link>
        <Link href="?filter=a-m">A-M</Link>
        <Link href="?filter=n-z">N-Z</Link>
        <div>Current filter: {filter || 'none'}</div>
        <div>Current search: {search || 'none'}</div>
        <input value={data.search || ''} onChange={handleSearchChange} placeholder="Search..." />
      </div>
    </div>
  )
}

// packages/vue3/test-app/Pages/InfiniteScroll/Filtering.vue
<script setup lang="ts">
import { InfiniteScroll, Link, useForm } from '@laraxgram/vue3'
import { debounce } from 'es-toolkit'
import { watch } from 'vue'
import { User, default as UserCard } from './UserCard.vue'

const props = defineProps<{
  users: { data: User[] }
  preserveState: boolean
  filter?: string
  search?: string
}>()

const form = useForm({
  filter: undefined,
  page: undefined,
  search: props.search,
})

watch(
  () => form.search,
  debounce(
    () =>
      form.get(
        '',
        props.preserveState
          ? {
              preserveState: true,
              replace: true,
              only: ['users', 'search', 'filter'],
              reset: ['users'],
            }
          : {
              replace: true,
            },
      ),
    250,
  ),
)
</script>

<template>
  <div>
    <div style="margin-bottom: 20px; display: flex; gap: 10px">
      <Link href=""> No Filter </Link>
      <Link href="?filter=a-m"> A-M </Link>
      <Link href="?filter=n-z"> N-Z </Link>
      <div>Current filter: {{ filter || 'none' }}</div>
      <div>Current search: {{ search || 'none' }}</div>
      <input v-model="form.search" placeholder="Search..." />
    </div>

    <InfiniteScroll data="users" style="display: grid; gap: 20px">
      <UserCard v-for="user in users.data" :key="user.id" :user="user" />

      <template #loading>
        <div style="text-align: center; padding: 20px">Loading...</div>
      </template>
    </InfiniteScroll>

    <div style="margin-top: 20px; display: flex; gap: 10px">
      <Link href=""> No Filter </Link>
      <Link href="?filter=a-m"> A-M </Link>
      <Link href="?filter=n-z"> N-Z </Link>
      <div>Current filter: {{ filter || 'none' }}</div>
      <div>Current search: {{ search || 'none' }}</div>
      <input v-model="form.search" placeholder="Search..." />
    </div>
  </div>
</template>
