// packages/svelte/test-app/Pages/History/Page.svelte
<script lang="ts">
  import { luna, router } from '@laraxgram/svelte'

  let { pageNumber, multiByte } = $props()
</script>

<a href="/history/1" use:luna>Page 1</a>
<a href="/history/2" use:luna>Page 2</a>
<a href="/history/3" use:luna>Page 3</a>
<a href="/history/4" use:luna>Page 4</a>
<a href="/history/5" use:luna>Page 5</a>

<button onclick={() => router.clearHistory()}>Clear History</button>

<div>This is page {pageNumber}.</div>
<div>Multi byte character: {multiByte}</div>

<div style="height: 5000px"></div>

// packages/react/test-app/Pages/History/Page.tsx
import { Link, router } from '@laraxgram/react'

export default ({ pageNumber, multiByte }: { pageNumber: string; multiByte: string }) => {
  const clearHistory = () => {
    router.clearHistory()
  }

  return (
    <>
      <Link href="/history/1">Page 1</Link>
      <Link href="/history/2">Page 2</Link>
      <Link href="/history/3">Page 3</Link>
      <Link href="/history/4">Page 4</Link>
      <Link href="/history/5">Page 5</Link>

      <button onClick={clearHistory}>Clear History</button>

      <div>This is page {pageNumber}.</div>
      <div>Multi byte character: {multiByte}</div>

      <div style={{ height: '5000px' }}></div>
    </>
  )
}
