// packages/vue3/test-app/Pages/FormComponent/TypeScript/Types.vue
<!-- This component is used for checking the TypeScript implementation; there is no Playwright test depending on it. -->
<script setup lang="ts">
import type { FormComponentOnSubmitCompleteArguments } from '@laraxgram/luna'
import { createForm } from '@laraxgram/vue3'

interface UserForm {
  name: string
  email: string
}

const TypedForm = createForm<UserForm>()

function handleSubmitComplete({ reset }: FormComponentOnSubmitCompleteArguments<UserForm>) {
  reset('name')
  reset('email')
}
</script>

<template>
  <div>
    <TypedForm
      method="post"
      action="/form-component/types"
      :reset-on-success="['name', 'email']"
      :reset-on-error="['name']"
      :on-submit-complete="handleSubmitComplete"
    >
      <template #default="{ errors, getData, clearErrors, reset }">
        {{ errors.name }} {{ errors.email }} {{ getData().name }} {{ getData().email }}
        {{ clearErrors('name', 'email') }}
        {{ reset('name') }}
        {{ reset('email') }}
        <div>Form content</div>
      </template>
    </TypedForm>

    <TypedForm method="post" action="/form-component/types" :reset-on-success="true" :reset-on-error="false">
      <template #default>
        <div>Boolean reset</div>
      </template>
    </TypedForm>
  </div>
</template>

// packages/svelte/test-app/Pages/FormComponent/TypeScript/Types.svelte
<!-- This component is used for checking the TypeScript implementation; there is no Playwright test depending on it. -->
<script lang="ts">
  import type { FormComponentOnSubmitCompleteArguments } from '@laraxgram/luna'
  import { createForm } from '@laraxgram/svelte'

  interface UserForm {
    name: string
    email: string
  }

  const TypedForm = createForm<UserForm>()

  function handleSubmitComplete({ reset }: FormComponentOnSubmitCompleteArguments<UserForm>) {
    reset('name')
    reset('email')
  }
</script>

<TypedForm
  method="post"
  action="/form-component/types"
  resetOnSuccess={['name', 'email']}
  resetOnError={['name']}
  onSubmitComplete={handleSubmitComplete}
>
  {#snippet children({ errors, getData, clearErrors, reset })}
    {errors.name}
    {errors.email}
    {getData().name}
    {getData().email}
    {clearErrors('name', 'email')}
    {reset('name')}
    {reset('email')}
    <div>Form content</div>
  {/snippet}
</TypedForm>

<TypedForm method="post" action="/form-component/types" resetOnSuccess={true} resetOnError={false}>
  <div>Boolean reset</div>
</TypedForm>
