// packages/svelte/test-app/Pages/FormComponent/Options.svelte
<script lang="ts">
  import type { Method, QueryStringArrayFormatOption } from '@laraxgram/luna'
  import { Form } from '@laraxgram/svelte'
  import Article from '../Article.svelte'

  let only: string[] = $state([])
  let except: string[] = $state([])
  let reset: string[] = $state([])
  let replace = $state(false)
  let _state = $state('Default State')
  let preserveScroll = $state(false)
  let preserveState = $state(false)
  let preserveUrl = $state(false)
  let queryStringArrayFormat: QueryStringArrayFormatOption | undefined = $state(undefined)

  function setOnly() {
    only = ['users']
  }

  function setExcept() {
    except = ['stats']
  }

  function setReset() {
    reset = ['orders']
  }

  function enableReplace() {
    replace = true
  }

  function enablePreserveScroll() {
    preserveScroll = true
  }

  function enablePreserveState() {
    preserveState = true
    _state = 'Replaced State'
  }

  function enablePreserveUrl() {
    preserveUrl = true
  }

  let action = $derived(
    (() => {
      if (preserveScroll) {
        return '/article'
      }

      if (preserveState) {
        return '/form-component/options'
      }

      if (preserveUrl) {
        return '/form-component/options?page=2'
      }

      return queryStringArrayFormat ? '/dump/get' : '/dump/post'
    })(),
  )

  let method = $derived(
    (() => {
      if (preserveScroll || preserveState || preserveUrl) {
        return 'get'
      }

      return queryStringArrayFormat ? 'get' : 'post'
    })() as Method,
  )

  let options = $derived({
    only,
    except,
    reset,
    replace,
    preserveScroll,
    preserveState,
    preserveUrl,
  })
</script>

<Form {action} {method} {options} {queryStringArrayFormat}>
  <h1>Form Options</h1>

  <input type="text" name="tags[]" value="alpha" readonly />
  <input type="text" name="tags[]" value="beta" readonly />

  <div>
    State: <span id="state">{_state}</span>
  </div>

  <div>
    <button type="button" onclick={setOnly}>Set Only (users)</button>
    <button type="button" onclick={setExcept}>Set Except (stats)</button>
    <button type="button" onclick={setReset}>Set Reset (orders)</button>
    <button type="button" onclick={() => (queryStringArrayFormat = 'brackets')}>Use Brackets Format</button>
    <button type="button" onclick={() => (queryStringArrayFormat = 'indices')}>Use Indices Format</button>
    <button type="button" onclick={enablePreserveScroll}>Enable Preserve Scroll</button>
    <button type="button" onclick={enablePreserveState}>Enable Preserve State</button>
    <button type="button" onclick={enablePreserveUrl}>Enable Preserve URL</button>
    <button type="button" onclick={enableReplace}>Enable Replace</button>
    <button type="submit">Submit</button>
  </div>

  {#if preserveScroll}
    <Article />
  {/if}
</Form>

// packages/react/test-app/Pages/FormComponent/Options.tsx
import type { Method, QueryStringArrayFormatOption } from '@laraxgram/luna'
import { Form } from '@laraxgram/react'
import { useMemo, useState } from 'react'
import Article from './../Article'

export default () => {
  const [only, setOnlyValues] = useState<string[]>([])
  const [except, setExceptValues] = useState<string[]>([])
  const [reset, setResetValues] = useState<string[]>([])
  const [replace, setReplace] = useState(false)
  const [state, setState] = useState('Default State')
  const [preserveScroll, setPreserveScroll] = useState(false)
  const [preserveState, setPreserveState] = useState(false)
  const [preserveUrl, setPreserveUrl] = useState(false)
  const [queryStringArrayFormat, setQueryStringArrayFormat] = useState<QueryStringArrayFormatOption | undefined>(
    undefined,
  )

  function setOnly() {
    setOnlyValues(['users'])
  }

  function setExcept() {
    setExceptValues(['stats'])
  }

  function setReset() {
    setResetValues(['orders'])
  }

  function enableReplace() {
    setReplace(true)
  }

  function enablePreserveScroll() {
    setPreserveScroll(true)
  }

  function enablePreserveState() {
    setPreserveState(true)
    setState('Replaced State')
  }

  function enablePreserveUrl() {
    setPreserveUrl(true)
  }

  const action = useMemo(() => {
    if (preserveScroll) {
      return '/article'
    }

    if (preserveState) {
      return '/form-component/options'
    }

    if (preserveUrl) {
      return '/form-component/options?page=2'
    }

    return queryStringArrayFormat ? '/dump/get' : '/dump/post'
  }, [preserveScroll, preserveState, preserveUrl, queryStringArrayFormat])

  const method = useMemo((): Method => {
    if (preserveScroll || preserveState || preserveUrl) {
      return 'get'
    }

    return queryStringArrayFormat ? 'get' : 'post'
  }, [preserveScroll, preserveState, preserveUrl, queryStringArrayFormat])

  return (
    <Form
      action={action}
      method={method}
      options={{
        only,
        except,
        reset,
        replace,
        preserveScroll,
        preserveState,
        preserveUrl,
      }}
      queryStringArrayFormat={queryStringArrayFormat}
    >
      {() => (
        <>
          <h1>Form Options</h1>

          <input type="text" name="tags[]" value="alpha" readOnly />
          <input type="text" name="tags[]" value="beta" readOnly />

          <div>
            State: <span id="state">{state}</span>
          </div>

          <div>
            <button type="button" onClick={setOnly}>
              Set Only (users)
            </button>
            <button type="button" onClick={setExcept}>
              Set Except (stats)
            </button>
            <button type="button" onClick={setReset}>
              Set Reset (orders)
            </button>
            <button type="button" onClick={() => setQueryStringArrayFormat('brackets')}>
              Use Brackets Format
            </button>
            <button type="button" onClick={() => setQueryStringArrayFormat('indices')}>
              Use Indices Format
            </button>
            <button type="button" onClick={enablePreserveScroll}>
              Enable Preserve Scroll
            </button>
            <button type="button" onClick={enablePreserveState}>
              Enable Preserve State
            </button>
            <button type="button" onClick={enablePreserveUrl}>
              Enable Preserve URL
            </button>
            <button type="button" onClick={enableReplace}>
              Enable Replace
            </button>
            <button type="submit">Submit</button>
          </div>

          {preserveScroll && <Article />}
        </>
      )}
    </Form>
  )
}
