// packages/svelte/test-app/Pages/FormComponent/Progress.svelte
<script lang="ts">
  import { Form } from '@laraxgram/svelte'
  import { onMount, onDestroy } from 'svelte'

  let showProgress: boolean | undefined = $state(undefined)
  let nprogressVisible = false
  let nprogressAppearances = $state(0)
  let observer: MutationObserver | null = null

  function disableProgress() {
    showProgress = false
  }

  onMount(() => {
    observer = new MutationObserver(() => {
      const nprogressElement = document.querySelector('#nprogress') as HTMLElement | null
      const nprogressIsCurrentlyVisible =
        nprogressElement &&
        ('popover' in HTMLElement.prototype
          ? nprogressElement.matches(':popover-open')
          : nprogressElement.style.display !== 'none')

      if (nprogressIsCurrentlyVisible) {
        if (!nprogressVisible) {
          nprogressVisible = true
          nprogressAppearances = nprogressAppearances + 1
        }
      } else {
        nprogressVisible = false
      }
    })

    observer.observe(document.body, { childList: true, subtree: true })
  })

  onDestroy(() => {
    if (observer) {
      observer.disconnect()
    }
  })
</script>

<Form action="/form-component/progress" method="post" {showProgress}>
  <h1>Progress</h1>

  <div>
    Nprogress appearances: <span id="nprogress-appearances">{nprogressAppearances}</span>
  </div>

  <div>
    <button type="button" onclick={disableProgress}>Disable Progress</button>
    <button type="submit">Submit</button>
  </div>
</Form>

// packages/react/test-app/Pages/FormComponent/Progress.tsx
import { Form } from '@laraxgram/react'
import { useEffect, useRef, useState } from 'react'

export default () => {
  const [showProgress, setShowProgress] = useState<boolean | undefined>(undefined)
  const [nprogressVisible, setNprogressVisible] = useState(false)
  const [nprogressAppearances, setNprogressAppearances] = useState(0)

  const observerRef = useRef<MutationObserver | null>(null)

  function disableProgress() {
    setShowProgress(false)
  }

  useEffect(() => {
    observerRef.current = new MutationObserver(() => {
      const nprogressElement = document.querySelector('#nprogress') as HTMLElement | null
      const nprogressIsCurrentlyVisible =
        nprogressElement &&
        ('popover' in HTMLElement.prototype
          ? nprogressElement.matches(':popover-open')
          : nprogressElement.style.display !== 'none')

      if (nprogressIsCurrentlyVisible) {
        if (!nprogressVisible) {
          setNprogressVisible(true)
          setNprogressAppearances((previousCount) => previousCount + 1)
        }
      } else {
        setNprogressVisible(false)
      }
    })

    observerRef.current.observe(document.body, { childList: true, subtree: true })

    return () => observerRef.current?.disconnect()
  }, [nprogressVisible])

  return (
    <Form action="/form-component/progress" method="post" showProgress={showProgress}>
      <h1>Progress</h1>

      <div>
        Nprogress appearances: <span id="nprogress-appearances">{nprogressAppearances}</span>
      </div>

      <div>
        <button type="button" onClick={disableProgress}>
          Disable Progress
        </button>
        <button type="submit">Submit</button>
      </div>
    </Form>
  )
}
