// packages/svelte/test-app/Pages/FormComponent/AsyncOnSuccess.svelte
<script lang="ts">
  import { Form } from '@laraxgram/svelte'

  const onSuccess = () => new Promise<void>((resolve) => setTimeout(resolve, 1500))
</script>

<div>
  <h1>Form Async OnSuccess Test</h1>

  <Form method="post" action="/form-component/async-on-success/submit" disableWhileProcessing {onSuccess}>
    {#snippet children()}
      <div>
        <input type="text" name="name" placeholder="Name" value="John Doe" />
      </div>

      <div>
        <button type="submit">Submit</button>
      </div>
    {/snippet}
  </Form>
</div>

// packages/vue3/test-app/Pages/FormComponent/AsyncOnSuccess.vue
<script setup lang="ts">
import { Form } from '@laraxgram/vue3'

const onSuccess = () => new Promise<void>((resolve) => setTimeout(resolve, 1500))
</script>

<template>
  <div>
    <h1>Form Async OnSuccess Test</h1>

    <Form
      method="post"
      action="/form-component/async-on-success/submit"
      disable-while-processing
      :on-success="onSuccess"
    >
      <div>
        <input type="text" name="name" placeholder="Name" value="John Doe" />
      </div>

      <div>
        <button type="submit">Submit</button>
      </div>
    </Form>
  </div>
</template>
