// packages/svelte/test-app/Pages/FormComponent/Methods.svelte
<script lang="ts">
  import type { Method } from '@lunajs/core'
  import { Form } from '@lunajs/svelte'

  let method: Method = $state('get')
</script>

<div>
  <h1>HTTP Methods</h1>

  <div>
    <button onclick={() => (method = 'get')}>GET</button>
    <button onclick={() => (method = 'post')}>POST</button>
    <button onclick={() => (method = 'put')}>PUT</button>
    <button onclick={() => (method = 'patch')}>PATCH</button>
    <button onclick={() => (method = 'delete')}>DELETE</button>
  </div>

  <div>Current method: {method}</div>

  <Form action={`/dump/${method}`} {method}>
    <div>
      <input type="text" name="name" placeholder="Name" value="John Doe" />
    </div>

    <div>
      <label for="active">Active</label>
      <input type="checkbox" name="active" id="active" value="true" checked />
    </div>

    <div>
      <button type="submit">
        Submit {method.toUpperCase()}
      </button>
    </div>
  </Form>
</div>

// packages/vue3/test-app/Pages/FormComponent/Methods.vue
<script setup lang="ts">
import type { Method } from '@lunajs/core'
import { Form } from '@lunajs/vue3'
import { ref } from 'vue'

const method = ref<Method>('get')
</script>

<template>
  <div>
    <h1>HTTP Methods</h1>

    <div>
      <button @click="method = 'get'">GET</button>
      <button @click="method = 'post'">POST</button>
      <button @click="method = 'put'">PUT</button>
      <button @click="method = 'patch'">PATCH</button>
      <button @click="method = 'delete'">DELETE</button>
    </div>

    <div>Current method: {{ method }}</div>

    <Form :action="`/dump/${method}`" :method="method">
      <div>
        <input type="text" name="name" placeholder="Name" value="John Doe" />
      </div>

      <div>
        <input type="checkbox" name="active" value="true" checked />
        <label>Active</label>
      </div>

      <div>
        <button type="submit">Submit {{ method.toUpperCase() }}</button>
      </div>
    </Form>
  </div>
</template>
