// packages/react/test-app/Pages/Prefetch/Tags.tsx
import { Link, router, useForm } from '@lunajs/react'

export default ({ pageNumber, lastLoaded, propType }: { pageNumber: number; lastLoaded: number; propType: string }) => {
  const form = useForm({
    name: '',
  })

  const flushUserTags = () => {
    router.flushByCacheTags(propType === 'string' ? 'user' : ['user'])
  }

  const flushUserProductTags = () => {
    router.flushByCacheTags(['user', 'product'])
  }

  const programmaticPrefetch = () => {
    router.prefetch('/prefetch/tags/2', { method: 'get' }, { cacheTags: propType === 'string' ? 'user' : ['user'] })
    router.prefetch(
      '/prefetch/tags/3',
      { method: 'get' },
      { cacheFor: '1m', cacheTags: propType === 'string' ? 'product' : ['product'] },
    )
    router.prefetch(
      '/prefetch/tags/6',
      { method: 'get' },
      { cacheFor: '1m' }, // No tags (untagged)
    )
  }

  const submitWithUserInvalidation = (e: React.MouseEvent) => {
    e.preventDefault()
    form.post('/dump/post', {
      invalidateCacheTags: propType === 'string' ? 'user' : ['user'],
    })
  }

  return (
    <div>
      <div id="links">
        <Link href="/prefetch/tags/1" prefetch="hover" cacheTags={['user', 'profile']}>
          User Page 1
        </Link>
        <Link href="/prefetch/tags/2" prefetch="hover" cacheTags={['user', 'settings']}>
          User Page 2
        </Link>
        <Link href="/prefetch/tags/3" prefetch="hover" cacheTags={['product', 'catalog']}>
          Product Page 3
        </Link>
        <Link href="/prefetch/tags/4" prefetch="hover" cacheTags={['product', 'details']}>
          Product Page 4
        </Link>
        <Link href="/prefetch/tags/5" prefetch="hover" cacheTags={propType === 'string' ? 'admin' : ['admin']}>
          Admin Page 5
        </Link>
        <Link href="/prefetch/tags/6" prefetch="hover">
          Untagged Page 6
        </Link>
      </div>
      <div id="controls">
        <button id="flush-user" onClick={flushUserTags}>
          Flush User Tags
        </button>
        <button id="flush-user-product" onClick={flushUserProductTags}>
          Flush User + Product Tags
        </button>
        <button id="programmatic-prefetch" onClick={programmaticPrefetch}>
          Programmatic Prefetch
        </button>
      </div>

      <div id="form-section">
        <h3>Form Test</h3>
        <form onSubmit={(e) => e.preventDefault()}>
          <input
            id="form-name"
            value={form.data.name}
            onChange={(e) => form.setData('name', e.target.value)}
            type="text"
            placeholder="Enter name"
          />
          <button id="submit-invalidate-user" onClick={submitWithUserInvalidation}>
            Submit (Invalidate User)
          </button>
        </form>
      </div>

      <div>
        <div>This is tags page {pageNumber}</div>
        <div>
          Last loaded at <span id="last-loaded">{lastLoaded}</span>
        </div>
      </div>
    </div>
  )
}

// packages/svelte/test-app/Pages/Prefetch/Tags.svelte
<script lang="ts">
  import { createBubbler, preventDefault } from 'svelte/legacy'

  const bubble = createBubbler()
  import { luna, router, useForm } from '@lunajs/svelte'
  interface Props {
    /* eslint-disable  @typescript-eslint/no-explicit-any */
    pageNumber: any
    /* eslint-disable  @typescript-eslint/no-explicit-any */
    lastLoaded: any
    propType: string
  }

  let { pageNumber, lastLoaded, propType }: Props = $props()

  const form = useForm({
    name: '',
  })

  function flushUserTags() {
    router.flushByCacheTags(propType === 'string' ? 'user' : ['user'])
  }

  function flushUserProductTags() {
    router.flushByCacheTags(['user', 'product'])
  }

  function programmaticPrefetch() {
    router.prefetch('/prefetch/tags/2', { method: 'get' }, { cacheTags: propType === 'string' ? 'user' : ['user'] })
    router.prefetch(
      '/prefetch/tags/3',
      { method: 'get' },
      { cacheFor: '1m', cacheTags: propType === 'string' ? 'product' : ['product'] },
    )
    router.prefetch(
      '/prefetch/tags/6',
      { method: 'get' },
      { cacheFor: '1m' }, // No tags (untagged)
    )
  }

  function submitWithUserInvalidation() {
    form.post('/dump/post', {
      invalidateCacheTags: propType === 'string' ? 'user' : ['user'],
    })
  }
</script>

<div>
  <div id="links">
    <a href="/prefetch/tags/1" use:luna={{ prefetch: 'hover', cacheTags: ['user', 'profile'] }}> User Page 1 </a>
    <a href="/prefetch/tags/2" use:luna={{ prefetch: 'hover', cacheTags: ['user', 'settings'] }}> User Page 2 </a>
    <a href="/prefetch/tags/3" use:luna={{ prefetch: 'hover', cacheTags: ['product', 'catalog'] }}>
      Product Page 3
    </a>
    <a href="/prefetch/tags/4" use:luna={{ prefetch: 'hover', cacheTags: ['product', 'details'] }}>
      Product Page 4
    </a>
    <a
      href="/prefetch/tags/5"
      use:luna={{ prefetch: 'hover', cacheTags: propType === 'string' ? 'admin' : ['admin'] }}
    >
      Admin Page 5
    </a>
    <a href="/prefetch/tags/6" use:luna={{ prefetch: 'hover' }}> Untagged Page 6 </a>
  </div>
  <div id="controls">
    <button id="flush-user" onclick={flushUserTags}> Flush User Tags </button>
    <button id="flush-user-product" onclick={flushUserProductTags}> Flush User + Product Tags </button>
    <button id="programmatic-prefetch" onclick={programmaticPrefetch}> Programmatic Prefetch </button>
  </div>

  <div id="form-section">
    <h3>Form Test</h3>
    <form onsubmit={preventDefault(bubble('submit'))}>
      <input id="form-name" bind:value={form.name} type="text" placeholder="Enter name" />
      <button id="submit-invalidate-user" onclick={submitWithUserInvalidation}> Submit (Invalidate User) </button>
    </form>
  </div>

  <div>
    <div>This is tags page {pageNumber}</div>
    <div>
      Last loaded at <span id="last-loaded">{lastLoaded}</span>
    </div>
  </div>
</div>
