// packages/svelte/test-app/Pages/Poll/HookManual.svelte
<script lang="ts">
  import { usePoll } from '@lunajs/svelte'

  const { start, stop } = usePoll(
    500,
    {
      only: ['custom_prop'],
      onFinish() {
        console.log('hook poll finished')
      },
    },
    {
      autoStart: false,
    },
  )
</script>

<button onclick={() => start()}>Start</button>
<button onclick={() => stop()}>Stop</button>

// packages/react/test-app/Pages/Poll/HookManual.tsx
import { usePoll } from '@lunajs/react'

export default () => {
  const { start, stop } = usePoll(
    500,
    {
      only: ['custom_prop'],
      onFinish() {
        console.log('hook poll finished')
      },
    },
    {
      autoStart: false,
    },
  )

  return (
    <>
      <button onClick={start}>Start</button>
      <button onClick={stop}>Stop</button>
    </>
  )
}
