// packages/svelte/test-app/Pages/LayoutProps/Basic.svelte
<script module lang="ts">
  import AppLayout from '@/Layouts/AppLayout.svelte'

  export const layout = [AppLayout, { title: 'Basic Layout Props', showSidebar: true }]
</script>

<script lang="ts">
  import { Link, setLayoutProps } from '@laraxgram/svelte'

  let sidebarVisible = $state(true)

  setLayoutProps({ showSidebar: true })

  function toggleSidebar() {
    sidebarVisible = !sidebarVisible
    setLayoutProps({ showSidebar: sidebarVisible })
  }
</script>

<div>
  <h2>Basic Layout Props Page</h2>
  <p>This page demonstrates setting layout props dynamically.</p>

  <div>
    <button type="button" onclick={toggleSidebar}>Toggle Sidebar</button>
    <span>Sidebar: {sidebarVisible ? 'visible' : 'hidden'}</span>
  </div>

  <div>
    <button type="button" onclick={() => setLayoutProps({ title: 'Updated Title' })}>Update Title</button>
  </div>

  <nav>
    <Link href="/layout-props/navigate">Go to Navigate Page</Link>
  </nav>
</div>

// packages/react/test-app/Pages/LayoutProps/Basic.tsx
import { Link, setLayoutProps } from '@laraxgram/react'
import { useState } from 'react'
import AppLayout from '../../Layouts/AppLayout'

const Basic = () => {
  const [sidebarVisible, setSidebarVisible] = useState(true)

  setLayoutProps({
    showSidebar: sidebarVisible,
  })

  return (
    <div>
      <h2>Basic Layout Props Page</h2>
      <p>This page demonstrates setting layout props dynamically.</p>

      <div>
        <button type="button" onClick={() => setSidebarVisible(!sidebarVisible)}>
          Toggle Sidebar
        </button>
        <span>Sidebar: {sidebarVisible ? 'visible' : 'hidden'}</span>
      </div>

      <div>
        <button type="button" onClick={() => setLayoutProps({ title: 'Updated Title' })}>
          Update Title
        </button>
      </div>

      <nav>
        <Link href="/layout-props/navigate">Go to Navigate Page</Link>
      </nav>
    </div>
  )
}

Basic.layout = [AppLayout, { title: 'Basic Layout Props', showSidebar: true }]

export default Basic
