// packages/svelte/test-app/Pages/WhenVisibleArrayReload.svelte
<script lang="ts">
  import { router, WhenVisible } from '@laraxgram/svelte'

  interface Props {
    firstData?:
      | {
          text: string
        }
      | undefined
    secondData?:
      | {
          text: string
        }
      | undefined
  }

  let { firstData = undefined, secondData = undefined }: Props = $props()

  const handleReload = () => {
    router.reload()
  }
</script>

<div>
  <h1>WhenVisible + Array Props + Reload</h1>

  <button onclick={handleReload}>Reload Page</button>

  <div style="margin-top: 2000px; padding: 20px; border: 1px solid #ccc">
    <WhenVisible data={['firstData', 'secondData']}>
      {#snippet fallback()}
        <p>Loading array data...</p>
      {/snippet}

      <div>
        <p>{firstData?.text}</p>
        <p>{secondData?.text}</p>
      </div>
    </WhenVisible>
  </div>
</div>

// packages/vue3/test-app/Pages/WhenVisibleArrayReload.vue
<script setup lang="ts">
import { router, WhenVisible } from '@laraxgram/vue3'

defineProps<{
  firstData?: {
    text: string
  }
  secondData?: {
    text: string
  }
}>()
</script>

<template>
  <div>
    <h1>WhenVisible + Array Props + Reload</h1>

    <button @click="router.reload()">Reload Page</button>

    <div style="margin-top: 2000px; padding: 20px; border: 1px solid #ccc">
      <WhenVisible :data="['firstData', 'secondData']">
        <template #fallback>
          <p>Loading array data...</p>
        </template>

        <div>
          <p>{{ firstData?.text }}</p>
          <p>{{ secondData?.text }}</p>
        </div>
      </WhenVisible>
    </div>
  </div>
</template>
