// packages/react/test-app/Pages/Poll/PreserveErrors.tsx
import { useForm, usePage, usePoll } from '@laraxgram/react'

export default ({ time }: { time: number }) => {
  const { errors } = usePage().props as { errors?: { name?: string } }
  const form = useForm({ name: '' })

  const submit = () => {
    form.post('/poll/preserve-errors')
  }

  usePoll(300, {
    only: ['time'],
  })

  return (
    <>
      {errors?.name && <p id="page-error">{errors.name}</p>}
      {form.errors.name && <p id="form-error">{form.errors.name}</p>}

      <button type="button" onClick={submit}>
        Submit
      </button>

      <p id="time">Time: {time}</p>
    </>
  )
}

// packages/vue3/test-app/Pages/Poll/PreserveErrors.vue
<script setup lang="ts">
import { useForm, usePoll } from '@laraxgram/vue3'

defineProps<{
  time: number
}>()

const form = useForm({
  name: '',
})

const submit = () => {
  form.post('/poll/preserve-errors')
}

usePoll(300, {
  only: ['time'],
})
</script>

<template>
  <p v-if="$page.props.errors?.name" id="page-error">{{ $page.props.errors.name }}</p>
  <p v-if="form.errors.name" id="form-error">{{ form.errors.name }}</p>

  <button type="button" @click="submit">Submit</button>

  <p id="time">Time: {{ time }}</p>
</template>
