// packages/svelte/test-app/Pages/Poll/UnchangedData.svelte
<script lang="ts">
  import { usePoll } from '@laraxgram/svelte'
  import { onMount } from 'svelte'

  let replaceStateCalls = $state(0)
  let pollsFinished = $state(0)

  onMount(() => {
    const original = window.history.replaceState.bind(window.history)
    window.history.replaceState = function (...args) {
      replaceStateCalls++
      return original(...args)
    }
  })

  usePoll(500, {
    only: ['custom_prop'],
    onFinish: () => pollsFinished++,
  })
</script>

<div>
  <p>replaceState calls: <span class="replaceStateCalls">{replaceStateCalls}</span></p>
  <p>polls finished: <span class="pollsFinished">{pollsFinished}</span></p>
</div>

// packages/vue3/test-app/Pages/Poll/UnchangedData.vue
<script setup lang="ts">
import { usePoll } from '@laraxgram/vue3'
import { onMounted, ref } from 'vue'

const replaceStateCalls = ref(0)
const pollsFinished = ref(0)

onMounted(() => {
  const original = window.history.replaceState.bind(window.history)
  window.history.replaceState = function (...args) {
    replaceStateCalls.value++
    return original(...args)
  }
})

usePoll(500, {
  only: ['custom_prop'],
  onFinish: () => pollsFinished.value++,
})
</script>

<template>
  <div>
    <p>
      replaceState calls: <span class="replaceStateCalls">{{ replaceStateCalls }}</span>
    </p>
    <p>
      polls finished: <span class="pollsFinished">{{ pollsFinished }}</span>
    </p>
  </div>
</template>
