// packages/svelte/test-app/Pages/UseHttp/Remember.svelte
<script lang="ts">
  import { Link, useHttp } from '@lunajs/svelte'

  const form = useHttp('useHttpRemember', {
    name: 'initial',
    email: '',
  })
</script>

<div>
  <h1>useHttp Remember Test</h1>

  <label>
    Name
    <input type="text" id="name" bind:value={form.name} />
  </label>

  <label>
    Email
    <input type="text" id="email" bind:value={form.email} />
  </label>

  <div id="current-values">Name: {form.name}, Email: {form.email}</div>
  <div id="is-dirty">isDirty: {form.isDirty}</div>

  <Link href="/dump/get" id="navigate-away">Navigate away</Link>
</div>

// packages/react/test-app/Pages/UseHttp/Remember.tsx
import { Link, useHttp } from '@lunajs/react'

export default () => {
  const form = useHttp('useHttpRemember', {
    name: 'initial',
    email: '',
  })

  return (
    <div>
      <h1>useHttp Remember Test</h1>

      <label>
        Name
        <input type="text" id="name" value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} />
      </label>

      <label>
        Email
        <input type="text" id="email" value={form.data.email} onChange={(e) => form.setData('email', e.target.value)} />
      </label>

      <div id="current-values">
        Name: {form.data.name}, Email: {form.data.email}
      </div>
      <div id="is-dirty">isDirty: {form.isDirty.toString()}</div>

      <Link href="/dump/get" id="navigate-away">
        Navigate away
      </Link>
    </div>
  )
}
