// packages/react/test-app/Pages/CustomConfig.tsx
import type { VisitOptions } from '@lunajs/core'
import { config, Link, useForm, usePage } from '@lunajs/react'

export default () => {
  const page = usePage()
  const form = useForm({})

  const submit = () => {
    form.post(page.url)
  }

  config.set({
    'form.recentlySuccessfulDuration': 1000,
    'prefetch.cacheFor': '2s',
  })

  config.set('visitOptions', (href: string, options: VisitOptions) => {
    if (href !== '/dump/post') {
      return {}
    }

    return { headers: { ...options.headers, 'X-From-Callback': 'bar' } }
  })

  return (
    <div>
      <Link prefetch href="/dump/get">
        Prefetch Link
      </Link>
      <Link method="post" headers={{ 'X-From-Link': 'foo' }} href="/dump/post">
        Post Dump
      </Link>
      <button onClick={submit}>Submit Form</button>
      {form.recentlySuccessful && <p>Form was recently successful!</p>}
    </div>
  )
}

// packages/svelte/test-app/Pages/CustomConfig.svelte
<script lang="ts">
  import type { VisitOptions } from '@lunajs/core'
  import { config, Link, useForm, page } from '@lunajs/svelte'

  const form = useForm({})

  const submit = () => {
    form.post(page.url)
  }

  config.set({
    'form.recentlySuccessfulDuration': 1000,
    'prefetch.cacheFor': '2s',
  })

  config.set('visitOptions', (href: string, options: VisitOptions) => {
    if (href !== '/dump/post') {
      return {}
    }

    return { headers: { ...options.headers, 'X-From-Callback': 'bar' } }
  })
</script>

<Link prefetch href="/dump/get">Prefetch Link</Link>
<Link method="post" headers={{ 'X-From-Link': 'foo' }} href="/dump/post">Post Dump</Link>
<button onclick={submit}>Submit Form</button>
{#if form.recentlySuccessful}
  <p>Form was recently successful!</p>
{/if}
