// packages/react/test-app/Pages/Dump.tsx
import type { Method } from '@lunajs/core'
import { usePage } from '@lunajs/react'
import { useEffect, useMemo } from 'react'
import type { MulterFile } from '../types'

export default ({
  headers,
  method,
  form,
  query,
  url,
  files,
}: {
  headers: Record<string, string>
  method: Method
  form: Record<string, unknown>
  query: Record<string, unknown>
  url: string
  files: MulterFile[] | object
}) => {
  const page = usePage()

  const dump = useMemo(
    () => ({
      headers,
      method,
      form,
      files: files ? files : {},
      query,
      url,
      $page: page,
    }),
    [headers, method, form, files, query, url, page],
  )

  useEffect(() => {
    window._luna_request_dump = dump
  }, [dump])

  return (
    <div>
      <div className="text">This is Luna page component containing a data dump of the request</div>
      <hr />
      <pre className="dump">{JSON.stringify(dump, null, 2)}</pre>
    </div>
  )
}

// packages/svelte/test-app/Pages/Dump.svelte
<script lang="ts">
  import type { Method } from '@lunajs/core'
  import { page } from '@lunajs/svelte'
  import type { MulterFile } from '../types'

  interface Props {
    headers: Record<string, string>
    method: Method
    form: Record<string, unknown>
    files: MulterFile[] | object
    url: string
    query: Record<string, unknown>
  }

  let { headers, method, form, files = {}, url, query }: Props = $props()

  // svelte-ignore state_referenced_locally
  const dump = {
    headers,
    method,
    form,
    files,
    query,
    url,
    page: page,
  }

  $effect(() => {
    window._luna_request_dump = dump
  })
</script>

<div>
  <div class="text">This is Luna page component containing a data dump of the request</div>
  <hr />
  <pre class="dump" style="white-space: pre-wrap; word-break: keep-all;">{JSON.stringify(dump)}</pre>
</div>
