// packages/vue3/test-app/Pages/WhenVisibleBackButton.vue
<script setup lang="ts">
import { Link, WhenVisible } from '@laraxgram/vue3'

defineProps<{
  lazyData?: {
    text: string
  }
}>()
</script>

<template>
  <div>
    <h1>WhenVisible + Back Button</h1>

    <Link href="/links/method">Navigate Away</Link>

    <div style="margin-top: 2000px; padding: 20px; border: 1px solid #ccc">
      <WhenVisible data="lazyData">
        <template #fallback>
          <p>Loading lazy data...</p>
        </template>

        <p>{{ lazyData?.text }}</p>
      </WhenVisible>
    </div>

    <div style="margin-top: 2000px; padding: 20px; border: 1px solid #ccc">
      <WhenVisible data="lazyData" always>
        <template #fallback>
          <p>Loading always data...</p>
        </template>

        <p>Always: {{ lazyData?.text }}</p>
      </WhenVisible>
    </div>
  </div>
</template>

// packages/svelte/test-app/Pages/WhenVisibleBackButton.svelte
<script lang="ts">
  import { Link, WhenVisible } from '@laraxgram/svelte'

  interface Props {
    lazyData?:
      | {
          text: string
        }
      | undefined
  }

  let { lazyData = undefined }: Props = $props()
</script>

<div>
  <h1>WhenVisible + Back Button</h1>

  <Link href="/links/method">Navigate Away</Link>

  <div style="margin-top: 2000px; padding: 20px; border: 1px solid #ccc">
    <WhenVisible data="lazyData">
      {#snippet fallback()}
        <p>Loading lazy data...</p>
      {/snippet}

      <p>{lazyData?.text}</p>
    </WhenVisible>
  </div>

  <div style="margin-top: 2000px; padding: 20px; border: 1px solid #ccc">
    <WhenVisible data="lazyData" always>
      {#snippet fallback()}
        <p>Loading always data...</p>
      {/snippet}

      <p>Always: {lazyData?.text}</p>
    </WhenVisible>
  </div>
</div>
