// packages/vue3/test-app/Pages/Flash/WithDeferred.vue
<script setup lang="ts">
import { Deferred, router, usePage } from '@laraxgram/vue3'
import { ref } from 'vue'

defineProps<{
  data?: string
}>()

const page = usePage()
const flashEventCount = ref(0)

router.on('flash', () => {
  flashEventCount.value++
})
</script>

<template>
  <div>
    <span id="flash">{{ JSON.stringify(page.flash) }}</span>
    <span id="flash-event-count">{{ flashEventCount }}</span>

    <Deferred data="data">
      <template #fallback>
        <div id="loading">Loading...</div>
      </template>
      <div id="data">{{ data }}</div>
    </Deferred>
  </div>
</template>

// packages/react/test-app/Pages/Flash/WithDeferred.tsx
import { Deferred, router, usePage } from '@laraxgram/react'
import { useRef, useState } from 'react'

export default ({ data }: { data?: string }) => {
  const page = usePage()
  const [flashEventCount, setFlashEventCount] = useState(0)
  const listenerSetup = useRef(false)

  if (!listenerSetup.current) {
    listenerSetup.current = true
    router.on('flash', () => {
      setFlashEventCount((n) => n + 1)
    })
  }

  return (
    <div>
      <span id="flash">{JSON.stringify(page.flash)}</span>
      <span id="flash-event-count">{flashEventCount}</span>

      <Deferred data="data" fallback={<div id="loading">Loading...</div>}>
        <div id="data">{data}</div>
      </Deferred>
    </div>
  )
}
