// packages/vue3/test-app/Pages/PersistentLayouts/Shorthand/Simple/PageB.vue
<script setup lang="ts">
import { Link } from '@laraxgram/vue3'
import Layout from '@/Layouts/SiteLayout.vue'

defineOptions({
  layout: Layout,
})
</script>

<template>
  <div>
    <span class="text">Simple Persistent Layout - Page B</span>
    <Link href="/persistent-layouts/shorthand/simple/page-a">Page A</Link>
  </div>
</template>

// packages/react/test-app/Pages/PersistentLayouts/RenderFunction/Simple/PageB.tsx
import { Link } from '@laraxgram/react'
import SiteLayout from '@/Layouts/SiteLayout.jsx'

const PageB = () => {
  return (
    <div>
      <span className="text">Simple Persistent Layout - Page B</span>
      <Link href="/persistent-layouts/render-function/simple/page-a">Page A</Link>
    </div>
  )
}

PageB.layout = (page: React.ReactNode) => <SiteLayout children={page} />

export default PageB
