// packages/svelte/test-app/Pages/SSR/Page1.svelte
<script lang="ts">
  import { luna, usePage } from '@lunajs/svelte'

  interface Props {
    user: { name: string; email: string }
    items: string[]
    count: number
  }

  let { user, items, count }: Props = $props()

  const page = usePage()
</script>

<div>
  <h1 data-testid="ssr-title">SSR Page 1</h1>

  <p data-testid="page-url">URL: {page.url}</p>

  <div data-testid="user-info">
    <p data-testid="user-name">Name: {user.name}</p>
    <p data-testid="user-email">Email: {user.email}</p>
  </div>

  <ul data-testid="items-list">
    {#each items as item (item)}
      <li data-testid="item">{item}</li>
    {/each}
  </ul>

  <p data-testid="count">Count: {count}</p>

  <a href="/ssr/page2" use:luna data-testid="navigate-link">Navigate to another page</a>
</div>

// packages/react/test-app/Pages/SSR/Page1.tsx
import { Link, usePage } from '@lunajs/react'

export default ({ user, items, count }: { user: { name: string; email: string }; items: string[]; count: number }) => {
  const page = usePage()

  return (
    <div>
      <h1 data-testid="ssr-title">SSR Page 1</h1>

      <p data-testid="page-url">URL: {page.url}</p>

      <div data-testid="user-info">
        <p data-testid="user-name">Name: {user.name}</p>
        <p data-testid="user-email">Email: {user.email}</p>
      </div>

      <ul data-testid="items-list">
        {items.map((item) => (
          <li key={item} data-testid="item">
            {item}
          </li>
        ))}
      </ul>

      <p data-testid="count">Count: {count}</p>

      <Link href="/ssr/page2" data-testid="navigate-link">
        Navigate to another page
      </Link>
    </div>
  )
}
