// packages/vue3/test-app/Pages/FormComponent/DataMethods.vue
<script setup lang="ts">
import { FormDataConvertible } from '@lunajs/core'
import { Form } from '@lunajs/vue3'

function testGetData(getData: () => Record<string, FormDataConvertible>) {
  const data = getData()
  console.log('getData result: ' + JSON.stringify(data))
}

function testGetFormData(getFormData: () => FormData) {
  const formData = getFormData()
  console.log('getFormData entries: ' + JSON.stringify(Object.fromEntries(formData.entries())))
}
</script>

<template>
  <div>
    <h1>Test getData() and getFormData() Methods</h1>

    <Form v-slot="{ getData, getFormData }">
      <input id="name" type="text" name="name" />

      <button type="button" @click="testGetData(getData)">Test getData()</button>

      <button type="button" @click="testGetFormData(getFormData)">Test getFormData()</button>
    </Form>
  </div>
</template>

// packages/svelte/test-app/Pages/FormComponent/DataMethods.svelte
<script lang="ts">
  import type { FormDataConvertible } from '@lunajs/core'
  import { Form } from '@lunajs/svelte'

  function testGetData(getData: () => Record<string, FormDataConvertible>) {
    const data = getData()
    console.log('getData result: ' + JSON.stringify(data))
  }

  function testGetFormData(getFormData: () => FormData) {
    const formData = getFormData()
    console.log('getFormData entries: ' + JSON.stringify(Object.fromEntries(formData.entries())))
  }
</script>

<div>
  <h1>Test getData() and getFormData() Methods</h1>

  <Form>
    {#snippet children({ getData, getFormData })}
      <input type="text" id="name" name="name" />

      <button type="button" onclick={() => testGetData(getData)}> Test getData() </button>

      <button type="button" onclick={() => testGetFormData(getFormData)}> Test getFormData() </button>
    {/snippet}
  </Form>
</div>
