// packages/svelte/test-app/Pages/Links/AsWarningFalse.svelte
<script lang="ts">
  import { luna } from '@laraxgram/svelte'

  let { method } = $props()
</script>

<div>
  <span class="text">This is the links page that demonstrates luna-links without the 'as' warning</span>

  <button use:luna={{ method, href: '/example' }} class="get">{method} button Link</button>
</div>

// packages/react/test-app/Pages/Links/AsWarningFalse.tsx
import type { Method } from '@laraxgram/luna'
import { Link } from '@laraxgram/react'

export default ({ method }: { method: Method }) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates luna-links without the 'as' warning</span>

      <Link method={method} href="/example" className="get" as="button">
        {method} button Link
      </Link>
    </div>
  )
}
