// packages/svelte/test-app/Pages/Links/PreserveScroll.svelte
<script module lang="ts">
  export { default as layout } from '@/Layouts/WithScrollRegion.svelte'
</script>

<script lang="ts">
  import type { Page } from '@lunajs/core'
  import { luna } from '@lunajs/svelte'

  interface Props {
    foo?: string
  }

  let { foo = 'default' }: Props = $props()

  const preserveCallback = (page: Page) => {
    console.log(JSON.stringify(page))

    return true
  }

  const preserveCallbackFalse = (page: Page) => {
    console.log(JSON.stringify(page))

    return false
  }
</script>

<div style="height: 800px; width: 600px">
  <span class="text">This is the links page that demonstrates scroll preservation with scroll regions</span>
  <span class="foo">Foo is now {foo}</span>

  <a
    href="/links/preserve-scroll-page-two"
    use:luna={{ preserveScroll: true, data: { foo: 'baz' } }}
    class="preserve"
    data-testid="preserve"
  >
    Preserve Scroll
  </a>
  <a href="/links/preserve-scroll-page-two" use:luna={{ data: { foo: 'bar' } }} class="reset" data-testid="reset">
    Reset Scroll
  </a>

  <a
    href="/links/preserve-scroll-page-two"
    use:luna={{ preserveScroll: preserveCallback, data: { foo: 'baz' } }}
    class="preserve-callback"
    data-testid="preserve-callback"
  >
    Preserve Scroll (Callback)
  </a>
  <a
    href="/links/preserve-scroll-page-two"
    use:luna={{ preserveScroll: preserveCallbackFalse, data: { foo: 'foo' } }}
    class="reset-callback"
    data-testid="reset-callback"
  >
    Reset Scroll (Callback)
  </a>

  <a href="/non-luna" class="off-site" style="display: block">Off-site link</a>

  <a href="/article" use:luna={{}} class="article" data-testid="article"> Article </a>
</div>

// packages/react/test-app/Pages/Links/PreserveScroll.tsx
import type { Page } from '@lunajs/core'
import { Link } from '@lunajs/react'
import WithScrollRegion from '@/Layouts/WithScrollRegion.jsx'

const PreserveScroll = ({ foo = 'default' }: { foo?: string }) => {
  const preserveCallback = (page: Page) => {
    console.log(JSON.stringify(page))
    return true
  }
  const preserveCallbackFalse = (page: Page) => {
    console.log(JSON.stringify(page))
    return false
  }

  return (
    <div style={{ height: '800px', width: '600px' }}>
      <span className="text">This is the links page that demonstrates scroll preservation with scroll regions</span>
      <span className="foo">Foo is now {foo}</span>

      <Link
        href="/links/preserve-scroll-page-two"
        preserveScroll
        data={{ foo: 'baz' }}
        data-testid="preserve"
        className="preserve"
      >
        Preserve Scroll
      </Link>
      <Link href="/links/preserve-scroll-page-two" data={{ foo: 'bar' }} data-testid="reset" className="reset">
        Reset Scroll
      </Link>

      <Link
        href="/links/preserve-scroll-page-two"
        preserveScroll={preserveCallback}
        data={{ foo: 'baz' }}
        data-testid="preserve-callback"
        className="preserve-callback"
      >
        Preserve Scroll (Callback)
      </Link>
      <Link
        href="/links/preserve-scroll-page-two"
        preserveScroll={preserveCallbackFalse}
        data={{ foo: 'foo' }}
        data-testid="reset-callback"
        className="reset-callback"
      >
        Reset Scroll (Callback)
      </Link>

      <a href="/non-luna" className="off-site">
        Off-site link
      </a>

      <Link href="/article" data-testid="article" className="article">
        Article
      </Link>
    </div>
  )
}

PreserveScroll.layout = (page: React.ReactNode) => <WithScrollRegion children={page} />

export default PreserveScroll
