// packages/svelte/test-app/Pages/Links/Reactivity.svelte
<script lang="ts">
  import type { CacheForOption, LinkPrefetchOption, Method } from '@lunajs/core'
  import { Link } from '@lunajs/svelte'

  let method: Method = $state('get')
  let href = $state('/dump/get')
  let data = $state({ foo: 'bar' })
  let headers = $state({ 'X-Custom-Header': 'value' })
  let prefetch: boolean | LinkPrefetchOption = $state(false)
  let cacheFor: CacheForOption = $state(0)

  function change() {
    method = 'post'
    href = '/dump/post'
    data = { foo: 'baz' }
    headers = { 'X-Custom-Header': 'new-value' }
  }

  function enablePrefetch() {
    prefetch = 'hover'
    cacheFor = '1s'
  }
</script>

<div>
  <span class="text">
    This page demonstrates reactivity in Luna links. Click the button to change the link properties.
  </span>

  <Link {method} {href} {data} {headers}>Submit</Link>

  <button onclick={change}>Change Link Props</button>

  <Link href="/dump/get" {prefetch} {cacheFor}>Prefetch Link</Link>

  <button onclick={enablePrefetch}>Enable Prefetch (1s cache)</button>
</div>

// packages/react/test-app/Pages/Links/Reactivity.tsx
import type { CacheForOption, LinkPrefetchOption, Method } from '@lunajs/core'
import { Link } from '@lunajs/react'
import { useState } from 'react'

export default () => {
  const [method, setMethod] = useState<Method>('get')
  const [href, setHref] = useState('/dump/get')
  const [data, setData] = useState({ foo: 'bar' })
  const [headers, setHeaders] = useState({ 'X-Custom-Header': 'value' })
  const [prefetch, setPrefetch] = useState<boolean | LinkPrefetchOption>(false)
  const [cacheFor, setCacheFor] = useState<CacheForOption>(0)

  const change = () => {
    setMethod('post')
    setHref('/dump/post')
    setData({ foo: 'baz' })
    setHeaders({ 'X-Custom-Header': 'new-value' })
  }

  const enablePrefetch = () => {
    setPrefetch('hover')
    setCacheFor('1s')
  }

  return (
    <div>
      <span className="text">
        This page demonstrates reactivity in Luna links. Click the button to change the link properties.
      </span>

      <Link method={method} href={href} data={data} headers={headers}>
        Submit
      </Link>

      <button onClick={change}>Change Link Props</button>

      <Link href="/dump/get" prefetch={prefetch} cacheFor={cacheFor}>
        Prefetch Link
      </Link>

      <button onClick={enablePrefetch}>Enable Prefetch (1s cache)</button>
    </div>
  )
}
