// packages/react/test-app/Pages/Reload/ConcurrentWithData.tsx
import { router, usePage } from '@lunajs/react'

export default () => {
  const { foo, bar, timeframe } = usePage<{ foo?: string; bar?: string; timeframe?: string }>().props

  function reloadBothPropsWithData() {
    router.reload({ only: ['foo'], data: { timeframe: 'week' } })
    setTimeout(() => router.reload({ only: ['bar'], data: { timeframe: 'week' } }), 50)
  }

  return (
    <div>
      <div id="foo">Foo: {foo}</div>
      <div id="bar">Bar: {bar}</div>
      <div id="timeframe">Timeframe: {timeframe}</div>

      <button onClick={reloadBothPropsWithData}>Reload both props with data</button>
    </div>
  )
}

// packages/svelte/test-app/Pages/Reload/ConcurrentWithData.svelte
<script lang="ts">
  import { router } from '@lunajs/svelte'

  let { foo, bar, timeframe }: { foo?: string; bar?: string; timeframe?: string } = $props()

  function reloadBothPropsWithData() {
    router.reload({ only: ['foo'], data: { timeframe: 'week' } })
    setTimeout(() => router.reload({ only: ['bar'], data: { timeframe: 'week' } }), 50)
  }
</script>

<div>
  <div id="foo">Foo: {foo}</div>
  <div id="bar">Bar: {bar}</div>
  <div id="timeframe">Timeframe: {timeframe}</div>

  <button onclick={reloadBothPropsWithData}>Reload both props with data</button>
</div>
