// packages/react/test-app/Pages/FormComponent/Precognition/WithAllErrorsConfig.tsx
import { config, Form } from '@laraxgram/react'

export default () => {
  // Set global config for withAllErrors (no prop on the Form component)
  config.set('form.withAllErrors', true)

  return (
    <div>
      <h1>Form Precognition - All Errors via Config</h1>

      <Form action="/precognition/with-all-errors" method="post" validationTimeout={100}>
        {({ invalid, errors, validate, valid, validating }) => (
          <>
            <div>
              <input name="name" placeholder="Name" onBlur={() => validate('name')} />
              {invalid('name') && (
                <div>
                  {Array.isArray(errors.name) ? (
                    errors.name.map((error, index) => (
                      <p key={index} id={`name-error-${index}`}>
                        {error}
                      </p>
                    ))
                  ) : (
                    <p id="name-error-0">{errors.name}</p>
                  )}
                </div>
              )}
              {valid('name') && <p>Name is valid!</p>}
            </div>

            <div>
              <input name="email" placeholder="Email" onBlur={() => validate('email')} />
              {invalid('email') && (
                <div>
                  {Array.isArray(errors.email) ? (
                    errors.email.map((error, index) => (
                      <p key={index} id={`email-error-${index}`}>
                        {error}
                      </p>
                    ))
                  ) : (
                    <p id="email-error-0">{errors.email}</p>
                  )}
                </div>
              )}
              {valid('email') && <p>Email is valid!</p>}
            </div>

            {validating && <p>Validating...</p>}
          </>
        )}
      </Form>
    </div>
  )
}

// packages/vue3/test-app/Pages/FormComponent/Precognition/WithAllErrorsConfig.vue
<script setup lang="ts">
import { config, Form } from '@laraxgram/vue3'

// Set global config for withAllErrors (no prop on the Form component)
config.set('form.withAllErrors', true)
</script>

<template>
  <div>
    <h1>Form Precognition - All Errors via Config</h1>

    <Form
      action="/precognition/with-all-errors"
      method="post"
      :validation-timeout="100"
      #default="{ invalid, errors, validate, valid, validating }"
    >
      <div>
        <input name="name" placeholder="Name" @blur="validate('name')" />
        <div v-if="invalid('name')">
          <template v-if="Array.isArray(errors.name)">
            <p v-for="(error, index) in errors.name" :key="index" :id="`name-error-${index}`">
              {{ error }}
            </p>
          </template>
          <p v-else id="name-error-0">{{ errors.name }}</p>
        </div>
        <p v-if="valid('name')">Name is valid!</p>
      </div>

      <div>
        <input name="email" placeholder="Email" @blur="validate('email')" />
        <div v-if="invalid('email')">
          <template v-if="Array.isArray(errors.email)">
            <p v-for="(error, index) in errors.email" :key="index" :id="`email-error-${index}`">
              {{ error }}
            </p>
          </template>
          <p v-else id="email-error-0">{{ errors.email }}</p>
        </div>
        <p v-if="valid('email')">Email is valid!</p>
      </div>

      <p v-if="validating">Validating...</p>
    </Form>
  </div>
</template>
