// packages/vue3/test-app/Pages/FormComponent/Precognition/TransformKeys.vue
<script setup lang="ts">
import { Form } from '@lunajs/vue3'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const transformData = (data: Record<string, any>) => {
  const document = data.document || {}
  return document
}
</script>

<template>
  <div>
    <h1>Form Precognition Transform Keys</h1>

    <Form action="/precognition/transform-keys" method="post" :validationTimeout="100" :transform="transformData">
      <template #default="{ invalid, errors, validate, valid, validating }">
        <div>
          <input
            id="email-input"
            name="document[customer][email]"
            placeholder="Email"
            @blur="() => validate('customer.email')"
          />
          <p v-if="invalid('customer.email')">{{ errors['customer.email'] }}</p>
          <p v-if="valid('customer.email')">Email is valid!</p>
        </div>

        <p v-if="validating">Validating...</p>
      </template>
    </Form>
  </div>
</template>

// packages/react/test-app/Pages/FormComponent/Precognition/TransformKeys.tsx
import { Form } from '@lunajs/react'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const transformData = (data: Record<string, any>) => {
  const document = data.document || {}
  return document
}

export default () => {
  return (
    <div>
      <h1>Form Precognition Transform Keys</h1>

      <Form action="/precognition/transform-keys" method="post" validationTimeout={100} transform={transformData}>
        {({ invalid, errors, validate, valid, validating }) => (
          <>
            <div>
              <input
                id="email-input"
                name="document[customer][email]"
                placeholder="Email"
                onBlur={() => validate('customer.email')}
              />
              {invalid('customer.email') && <p>{errors['customer.email']}</p>}
              {valid('customer.email') && <p>Email is valid!</p>}
            </div>

            {validating && <p>Validating...</p>}
          </>
        )}
      </Form>
    </div>
  )
}
