// packages/svelte/test-app/Pages/FormComponent/Precognition/WithAllErrorsConfig.svelte
<script lang="ts">
  import { config, Form } from '@laraxgram/svelte'

  // Set global config for withAllErrors (no prop on the Form component)
  config.set('form.withAllErrors', true)
</script>

<div>
  <h1>Form Precognition - All Errors via Config</h1>

  <Form action="/precognition/with-all-errors" method="post" validationTimeout={100}>
    {#snippet children({ invalid, errors, validate, valid, validating })}
      <div>
        <input name="name" placeholder="Name" onblur={() => validate('name')} />
        {#if invalid('name')}
          <div>
            {#if Array.isArray(errors.name)}
              {#each errors.name as error, index (index)}
                <p id="name-error-{index}">{error}</p>
              {/each}
            {:else}
              <p id="name-error-0">{errors.name}</p>
            {/if}
          </div>
        {/if}
        {#if valid('name')}
          <p>Name is valid!</p>
        {/if}
      </div>

      <div>
        <input name="email" placeholder="Email" onblur={() => validate('email')} />
        {#if invalid('email')}
          <div>
            {#if Array.isArray(errors.email)}
              {#each errors.email as error, index (index)}
                <p id="email-error-{index}">{error}</p>
              {/each}
            {:else}
              <p id="email-error-0">{errors.email}</p>
            {/if}
          </div>
        {/if}
        {#if valid('email')}
          <p>Email is valid!</p>
        {/if}
      </div>

      {#if validating}
        <p>Validating...</p>
      {/if}
    {/snippet}
  </Form>
</div>

// packages/react/test-app/Pages/FormComponent/Precognition/WithAllErrorsConfig.tsx
import { config, Form } from '@laraxgram/react'

export default () => {
  // Set global config for withAllErrors (no prop on the Form component)
  config.set('form.withAllErrors', true)

  return (
    <div>
      <h1>Form Precognition - All Errors via Config</h1>

      <Form action="/precognition/with-all-errors" method="post" validationTimeout={100}>
        {({ invalid, errors, validate, valid, validating }) => (
          <>
            <div>
              <input name="name" placeholder="Name" onBlur={() => validate('name')} />
              {invalid('name') && (
                <div>
                  {Array.isArray(errors.name) ? (
                    errors.name.map((error, index) => (
                      <p key={index} id={`name-error-${index}`}>
                        {error}
                      </p>
                    ))
                  ) : (
                    <p id="name-error-0">{errors.name}</p>
                  )}
                </div>
              )}
              {valid('name') && <p>Name is valid!</p>}
            </div>

            <div>
              <input name="email" placeholder="Email" onBlur={() => validate('email')} />
              {invalid('email') && (
                <div>
                  {Array.isArray(errors.email) ? (
                    errors.email.map((error, index) => (
                      <p key={index} id={`email-error-${index}`}>
                        {error}
                      </p>
                    ))
                  ) : (
                    <p id="email-error-0">{errors.email}</p>
                  )}
                </div>
              )}
              {valid('email') && <p>Email is valid!</p>}
            </div>

            {validating && <p>Validating...</p>}
          </>
        )}
      </Form>
    </div>
  )
}
