// packages/svelte/test-app/Pages/Remember/MultipleComponents.svelte
<script lang="ts">
  import { luna, useRemember } from '@lunajs/svelte'
  import ComponentA from '@/Pages/Remember/Components/ComponentA.svelte'
  import ComponentB from '@/Pages/Remember/Components/ComponentB.svelte'

  let untracked = $state('')

  const form = useRemember({
    name: '',
    remember: false,
  })
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="full_name" bind:value={form.name} />
  </label>
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={form.remember} />
  </label>
  <label>
    Untracked
    <input type="text" id="untracked" name="untracked" bind:value={untracked} />
  </label>

  <ComponentA class="component-a" />
  <ComponentB class="component-b" />

  <a href="/dump/get" use:luna class="link">Navigate away</a>
  <a href="/non-luna" class="off-site">Navigate off-site</a>
</div>

// packages/vue3/test-app/Pages/Remember/MultipleComponents.vue
<script setup lang="ts">
import { Link, useRemember } from '@lunajs/vue3'
import { ref } from 'vue'
import ComponentA from '@/Pages/Remember/Components/ComponentA.vue'
import ComponentB from '@/Pages/Remember/Components/ComponentB.vue'

const untracked = ref('')

const form = useRemember({
  name: '',
  remember: false,
})
</script>

<template>
  <div>
    <label>
      Full Name
      <input type="text" id="name" name="full_name" v-model="form.name" />
    </label>
    <label>
      Remember Me
      <input type="checkbox" id="remember" name="remember" v-model="form.remember" />
    </label>
    <label>
      Untracked
      <input type="text" id="untracked" name="untracked" v-model="untracked" />
    </label>

    <component-a class="component-a" />
    <component-b class="component-b" />

    <Link href="/dump/get" class="link">Navigate away</Link>
    <a href="/non-luna" class="off-site">Navigate off-site</a>
  </div>
</template>
