// packages/react/test-app/Pages/Remember/Object.tsx
import { Link, useRemember } from '@lunajs/react'
import { useState } from 'react'

export default () => {
  const [untracked, setUntracked] = useState('')

  const [form, setForm] = useRemember({ name: '', remember: false })

  return (
    <div>
      <label>
        Full Name
        <input
          type="text"
          id="name"
          name="full_name"
          value={form.name}
          onChange={(e) => setForm({ ...form, name: e.target.value })}
        />
      </label>
      <label>
        Remember Me
        <input
          type="checkbox"
          id="remember"
          name="remember"
          checked={form.remember}
          onChange={(e) => setForm({ ...form, remember: e.target.checked })}
        />
      </label>
      <label>
        Untracked
        <input
          type="text"
          id="untracked"
          name="untracked"
          value={untracked}
          onChange={(e) => setUntracked(e.target.value)}
        />
      </label>

      <Link href="/dump/get" className="link">
        Navigate away
      </Link>
    </div>
  )
}

// packages/vue3/test-app/Pages/Remember/Object.vue
<script setup lang="ts">
import { Link, useRemember } from '@lunajs/vue3'
import { ref } from 'vue'

const untracked = ref('')

const form = useRemember({
  name: '',
  remember: false,
})
</script>

<template>
  <div>
    <label>
      Full Name
      <input type="text" id="name" name="full_name" v-model="form.name" />
    </label>
    <label>
      Remember Me
      <input type="checkbox" id="remember" name="remember" v-model="form.remember" />
    </label>
    <label>
      Untracked
      <input type="text" id="untracked" name="untracked" v-model="untracked" />
    </label>

    <Link href="/dump/get" class="link">Navigate away</Link>
  </div>
</template>
