// packages/react/test-app/Pages/Head/Reactive.tsx
import { Head } from '@lunajs/react'
import { useState } from 'react'

export default () => {
  const [title, setTitle] = useState('Initial Title')
  const [description, setDescription] = useState('Initial description')

  const updateMeta = () => {
    setTitle('Updated Title')
    setDescription('Updated description')
  }

  return (
    <>
      <Head title={title}>
        <meta name="description" content={description} head-key="description" />
        <meta name="author" content="Test Author" />
      </Head>

      <div>
        <h1>Dynamic Head Updates</h1>
        <button id="update-meta" onClick={updateMeta}>
          Update Meta
        </button>
        <p>Current title: {title}</p>
        <p>Current description: {description}</p>
      </div>
    </>
  )
}

// packages/vue3/test-app/Pages/Head/Reactive.vue
<script setup lang="ts">
import { Head } from '@lunajs/vue3'
import { ref } from 'vue'

const title = ref('Initial Title')
const description = ref('Initial description')

function updateMeta() {
  title.value = 'Updated Title'
  description.value = 'Updated description'
}
</script>

<template>
  <Head :title="title">
    <meta name="description" :content="description" head-key="description" />
    <meta name="author" content="Test Author" />
  </Head>

  <div>
    <h1>Dynamic Head Updates</h1>
    <button id="update-meta" @click="updateMeta">Update Meta</button>
    <p>Current title: {{ title }}</p>
    <p>Current description: {{ description }}</p>
  </div>
</template>
